### ISSUE TITLE
[2.0.5-r9 (119)] Nexus 5 / 6.0.1 - Older notifications are getting disappeared when the user receives new notifications on "Notifications" screen.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1048]
Frequency: Every time

Precondition: User must have "25" received notifications under "Notification" screen.

Action: 
1: Launch the app and login with valid credentials.
2: Tap on "Notification" icon and note last received notification.
3: Tap on "<" back option and tap on "User" icon.
4: Tap on "Lomotif" tab and like/comment on own lomotif.
5: User will receive notifications.
6: Navigate to "Home" screen and tap on "Notification" icon.
7: Go to last notification.
8: Check if old notifications are getting disappeared when the user receives new notifications.

Expected result:
1: All older notifications should be displayed when the user receives new notifications.
2: There should not be a limit (25) for received notifications under "Notification" screen.

Actual result: 
1: Older notifications are getting disappeared when the user received new notifications on "Notifications" screen.
2: Only 25 notifications are getting loaded under "Notification" screen.

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.5-r9 (119)] on Sony Xperia Z5 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.5-r10 (120)] on Moto X Play / 6.0.1

**Comment by xiuie** [comment]
This issue has been verified fixed for [2.0.5-r10 (120)]
