### ISSUE TITLE
[2.0.5-r10 (120)] Samsung Galaxy S6 / 6.0.1 - Recently posted comment is not displayed under "Comments" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1057]
Frequency: Every time

Precondition:
- There should be some lomotifs under "Lomotifs" tab.

Action:
1: Launch the app and login with a valid credential.
2: Tap on "User Profile" icon and navigate to "Profile" screen.
3: Navigate to "Lomotifs" tab and open one "Lomotif"(User will be navigated to "Lomorif preview" screen).
4: Navigate to "Comments" screen, post one comment and immediately tap on "<" back(User will be navigated to "Lomotif Preview" screen).
5: Navigate back to "Comments" screen.
6: Check if the recently posted comment is displayed or not. 

Expected result: Recently posted comment should be displayed under "Comments" screen. 

Actual result: 
1: Recently posted comment is not displayed under "Comments" screen. 
2: Count is getting increased for recently posted comment but "Comment" is not displayed under "Comments" screen.

Note: Similar issue is observed from "Feeds" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ia0lCTFVIQm1oSlk

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.5-r10 (120)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Upon clarification, tester who logged this verified:  If we wait the comment gets posted and displayed under "Comments" screen.
