### ISSUE TITLE
[2.0.5-r10 (120)] Samsung Galaxy S6 / 6.0.1 - Likes effect(Red heart) and count are getting reset when user likes lomotif.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1059]
Frequency: Random

Precondition:
- There should be some lomotif under "Following" tab.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Following" tab and select one lomotif.
3: Double tap on lomotif, observed like effect and count are increased.
4: Unlike the lomotif and again like the lomotif.
5: After few secs,
6: Check if likes effect(Red heart) and the count are getting reset or not.

Expected result: Likes effect(Red heart) and the count should not get reset when the user likes lomotif.

Actual result: Likes effect(Red heart) and the count are getting reset when the user likes lomotif.

Note: 
1: Similar issue is observed from "Own profile>>Lomotifs tab>> Lomotif preview" screen.
2: Similarly from "Follow user>> searched user profile>>Lomotif preview" screen.
3: Similar issue is randomly observed when user like the lomotif for first time.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iOHREekFSZVNRRk0

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.5-r10 (120)] on Sony Xperia Z5 / 6.0.1

**Comment by ruiwen** [comment]
@Pankaj-Testershub @Aboli-Testershub I notice that in the video, the loading indicator was still spinning when the reset happened, which may indicate that the network is down. The reset to an unliked state is expected if the network call to perform the like fails, ie. the client provides feedback of the like first, then if the call fails, undoes the feedback (hence the reset).

Could you verify if it wasn't a network issue?

**Comment by Aboli-Testershub** [comment]
@ruiwen, Yes that was a network issue, cause it is working fine after spinning.

**Comment by ruiwen** [comment]
@Aboli-Testershub ok cool so we can close this then?

/cc @xiuie

**Comment by Aboli-Testershub** [comment]
@ruiwen, Yeah Sure, you can close this.
