### ISSUE TITLE
[1.0.15] Micromax P480/ android 5.0.1- "While playing the video device is going to the sleep mode".

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#106]
Action:
1.Set the device sleeping time as 15 sec.
2.Launch Lomotif app.
3.Play any Lomotif- 30 sec video and wait for 15 sec.
4.check whether the device is going to the sleep mode or not.

Expected result: While playing video the device should not go to the sleep mode.

Actual result: While playing  video the device is going to the sleep mode.

![sleep](https://cloud.githubusercontent.com/assets/12474351/14349528/5b3e7af8-fce1-11e5-8f95-2bfe94122e1a.png)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.15] on Sony xPeria Z / Android 5.1.1.

It should map with device permission.

**Comment by xiuie** [comment]
Refer to #109
