### ISSUE TITLE
[2.0.6-r1 (124)] Moto X Play - Continuous loading sign and "New Notification" message is displayed when user tap on "Sign up/Login" button under "Notification" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1102]
Frequency: Every time

Precondition:
- User should be log out from the app.

Action:
1: Launch the app.
2: Navigate to "Notification" screen and tap on "Sign up/login" button.
3: Check if the continuous loading sign and "New Notification" message is displayed or not.

Expected result: 
1: Continuous loading sign and "New Notification" message should not be displayed.
2: User should be navigated to "Sign up/Login" screen.

Actual result: Continuous loading sign and "New Notification" message is displayed when user tap on "Sign up/Login" button under "Notification" screen.
2: User is not able to "Sign up/Login" from "Notification" screen.

Refer the following screenshot for more details:
![loading_notifcation](https://cloud.githubusercontent.com/assets/24311318/23360952/21070ce0-fd14-11e6-8b67-6fff408782fb.jpg)

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Samsung Galaxy S6 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
