### ISSUE TITLE
[2.0.6-r1(124)] Samsung Galaxy S6 / 6.0.1 - Application is crashing when user tap on asset thumbnail on "Create" screen.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1103]
Frequency - Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START".
3: Select one motif from "Motif" tab and proceed to create screen with/without music.
4: Tap on asset thumbnail on "Create" screen.
5: Check if application is crashing or not.

Excepted Result: Application should not be crash when user tap on asset thumbnail on "Create" screen.

Actual Result: Application is crashing when user tap on asset thumbnail on "Create" screen.

**Note:** 
1: Edit options("+" and "-") are misaligned on "Create" screen. 
2: Assets thumbnails also misaligned.

Debug Details:
Device ID: e5e3a5cd-e1ff-408f-94c7-163b779ef746R
ADID: c1cb06cb-b7d6-4d06-b280-d83045215e47
Auth Key: e955fd6730ed6693a9823b0e0cd0d6e5a2b2b00d

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Sony Xperia Z5 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
