### ISSUE TITLE
[2.0.6-r1 (124)] Moto X Play / 6.0.1 - Motif categories title is not displayed under "Motifs" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1104]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START", user will be navigated to "Add Photos & Videos" screen and navigate to "Motifs" tab.
3: Check if Motif categories title is displayed or not.

Expected result: Motif categories title should be displayed under "Motifs" tab.

Actual result: Motif categories title is not displayed under "Motifs" tab.

Note: Similar issue is observed under the motifs category screen.

Refer the following screenshot for more details:
![title_motifs](https://cloud.githubusercontent.com/assets/24311318/23361332/2531d69a-fd16-11e6-9905-e5611355e44e.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Sony Xperia Z5 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
