### ISSUE TITLE
[2.0.6-r1 (124)] Moto X Play / 6.0.1 - Same motifs are displayed under all motifs categories.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1105]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on START, user will be navigated to "Add Photos & Videos" screen and navigate to "Motifs" tab.
3: Tap on any category and navigate to "Motif" category screen one by one.
4: Check if Same motifs are displayed under all motifs categories.

Expected result: Motifs should be displayed as per motif categories.

Actual result: Same motifs are displayed under all motifs categories.

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Sony Xperia Z5 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
