### ISSUE TITLE
[2.0.6-r1 (124)] Google Pixel / 7.1.1 - Application is crashing when user taps on "My Music" tab on "Find Music" screen.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1107]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START".
3: Select images/videos/motifs.
4: Navigate to "Find Music" screen and tap on "My Music" tab.
5: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user taps on "My Music" tab on "Find Music" screen.

Defect Debug Details:
Device ID: 7396221c-0c1c-46d8-9094-020b9eb62617R
ADID: 912d9c2a-d921-4c58-9870-5003404c0236
Auth Key: ea925bd8cd6cdccf3de1d1eed4a1f58f6883f9ed

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudODRTWkVJeXpaRms

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Samsung Galaxy S6 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
