### ISSUE TITLE
[2.0.6-r1 (124)] Google Pixel / 7.1.1 - User is not able to select motif after a single tap from "Motif" tab on "Add Photos & Videos" screen.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1108]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START" and navigate to "Motif" tab.
3: Tap to select motif (motif gets select).
4: Tap to select second motif.
5: Check if user is able to select second motif.

Expected result:
1: User should be able to select motif after the single tap from "Motif" tab on "Add Photos & Videos" screen.
2: Relevant selected count should be displayed after single tap to select the second motif.

Actual result:
1: User is not able to select motif after a single tap from "Motif" tab on "Add Photos & Videos" screen.
2: Selected count is getting reset after single to selecting the second motif from "Motif" tab.
3: User needs to double tap to select the second motif from "Motif" tab on "Add Photos & Videos" screen.

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudVFNzSnVqdVRPeHc

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Sony Xperia Z5 / 6.0.1

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Samsung Galaxy S6 / 6.0.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Moto X Play / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
