### ISSUE TITLE
[2.0.6-r1 (124)] Google Pixel / 7.1.1 - Search field is displayed as selected even when user has not tapped on "Search" field.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1109]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START", user will be on "Add Photos & Videos" screen and navigated to "Motifs" tab.
3: Check if Search field is displayed as selected or not.

Expected result: Search field is displayed as selected even when user has not tapped on "Search" field.

Actual result: Search field is displayed as selected even when user has not tapped on "Search" field.

Refer the following screenshot for more details:
 
![searched_tapped](https://cloud.githubusercontent.com/assets/24311318/23361997/8e0dee30-fd19-11e6-9dcc-4c601a179a49.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r1 (124)] on Samsung Galaxy S6 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
