### ISSUE TITLE
[2.0.6-r3 (127)] Google Pixel / 7.1.1 - The user is navigating to "Home" screen from "Find Music" screen after tapping on "<" back option on "Find Music" screen. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1120]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START" and navigate to "Add Photos & Videos" screen.
3: Select any Photo/Videos/Motif and navigate to "Find Music" screen.
4: Tap on "<" back option.
5: Check if the user is navigating to "Home" screen.

Expected result: The user should navigate to "Add Photos & Videos" screen after tapping on "<" back option on "Find Music" screen.

Actual result: The user is navigating to "Home" screen from "Find Music" screen after tapping on "<" option on "Find Music" screen. 

Please refer below video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudTXg1cGtXd09Sczg

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
