### ISSUE TITLE
[2.0.6-r3 (127)] Nexus 5 / 6.0.1 - Application is crashing when user is navigating to "Home" screen from "Add Photo & Videos" screen after tapping on "X" option.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1121]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START", user will be navigated to "Add Photos & Videos" screen.
3: Tap on "X" option, user will be navigated to "Home" screen and wait for few secs.
4: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user is navigating to "Home" screen from "Add Photo & Videos" screen after tapping on "X" option.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iNzhtYWZKRTdHNFE

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]
