### ISSUE TITLE
[2.0.6-r3 (127)] Sony Xperia Z5 / 6.0.1 - Selected motifs are displayed as deselected when user refreshed the "Motif" tab.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1125]
Frequency - Every Time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START".
3: Tap on "Motif" tab and select 5-6 motifs (which are displayed on screen).
4: Refresh the "Motif" tab.
5: Check if selected motifs are getting deselected or not.

Excepted Result: Selected motifs should not displayed as deselected when user refreshed the "Motif" tab.

Actual Result: 
1: Selected motifs are displayed as deselected when user refreshed the "Motif" tab.
2: Deselected motifs are displayed as selected when user expand the category.

For more details refer following video link:
https://drive.google.com/open?id=0B2TfWRODMVhYNkVzbDhUWEpBV0U

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
