### ISSUE TITLE
[2.0.6-r3 (127)] Google Pixel / 7.1.1 - Application crashes when user try to share lomotif via "Instagram/Messenger/Whatsapp/Facebook/Twitter/Facebook" on "Share" screen.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1126]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START".
3: Create lomotif with Photos/Videos/Motifs with/without music.
4: Tap on "Export" and navigate to "Share" screen.
5: Select "Facebook".
6: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing after tapping on "Facebook" option on "Share" screen.

**Note: This issue is specifically observed for 7 OS.**
It is working as expected for "Snapchat", "Message" and "Email" options.

Device Debug Details:
Device ID: cc1f9716-a0c9-4db6-a4c0-5ca253088b6fR
ADID: b184f010-8e34-411d-8920-c92e5f1249b0
Auth Key: 716e2b3febc13e78f91844948ea5a7babdfc7a82

Please refer below video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudTHp6cEJOeV9PcXM

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3] on One Plus 3T / 7.0

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Pankaj-Testershub** [comment]
@xiuie Verified.Fixed.
