### ISSUE TITLE
[2.0.6-r3 (127)] Samsung Galaxy S4 / 5.0.1 -  Motifs are not displayed as unselected when user select motifs from "Motif" tab and unselect them by expanding Motif category.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1129]
Frequency - Every Time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START".
3: Tap on "Motif" tab and select motif(which are displayed on screen) for particular category e.g Love.
4: Expand the motif category from which motifs are selected. 
5: Deselect the motifs which are selected and tap on "x" option.
6: Check if motifs are displayed as selected.

Excepted Result: Motifs should be displayed as unselected when user select motifs from "Motif" tab and unselect them by expanding Motif category.

Actual Result: Motifs are not displayed as unselected when user select motifs from "Motif" tab and unselect them by expanding Motif category.

For more details refer following video link:
https://drive.google.com/open?id=0Bx8fu9rzyCudWWVCYmxKclJzNzg

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie Verified Fix
