### ISSUE TITLE
[1.0.17] Dell Tab/ android 4.4.4 -"Selected videos are not deselecting when the user go to the previous folder and come back to the same  folder again".

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#113]
Action:
1.Launch Lomotif app.
2.Tap on start button.
3.Select any two or more created videos and go back to the previous folder.
4.Now come back to the same folder.
5.Check whether previously selected video is now selected or not.

Expected result:Once the user go out of the folder, videos should be deselected automatically.

Actual result: Selected videos are not deselecting when the user come back to the same folder again.

![pre1](https://cloud.githubusercontent.com/assets/12474351/14382398/21f075ba-fdab-11e5-8161-3ced30fc2097.png)

![pre2](https://cloud.githubusercontent.com/assets/12474351/14382399/21f5afd0-fdab-11e5-97bc-bf076aeee91d.png)

![pre3](https://cloud.githubusercontent.com/assets/12474351/14382400/21fb4a6c-fdab-11e5-9b66-c695be113177.png)

![pre4](https://cloud.githubusercontent.com/assets/12474351/14382405/23abde44-fdab-11e5-9325-69b51462169b.png)

![pre5](https://cloud.githubusercontent.com/assets/12474351/14382402/2235112a-fdab-11e5-9a71-3d4640643a78.png)

**Comment by xiuie** [comment]
@vinay97t This works as designed to allow users to select clips from different folders
