### ISSUE TITLE
[2.0.6-r3 (127)] Samsung Galaxy S6 / 6.0.1 - "Folder" title is displayed under "Album" tab and above the "Albums" folders when user simultaneously taps on any two folders from "Album" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1130]
Frequency: Every time

Action;
1: Launch the app and login with a valid credential.
2: Tap on "START", user will be navigated to "Add Photos & Videos" screen.
3: Simultaneously tap on any two folders from "Album" tab.
4: Check if "Folder" title is displayed under "Album" tab or not.

Expected result: "Folder" title should not display under "Album" tab and above the "Album" folders when the user simultaneously taps on any two folders from "Album" tab.

Actual result: 
1: "Folder" title is displayed under "Album" tab when the user simultaneously taps on any two folders from "Album" tab.
2: Blank white screen is displayed when the user taps on "X" option and when user refreshes the blank screen the "Assets" are displayed without any title.

**Note: 
1: Similar issue is observed after simultaneously tapping on any two folders.
2: Similar issue is observed under "Motifs" tab.**

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iN01wSUR4MnpNUzQ

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
