### ISSUE TITLE
[2.0.6-r3 (127)] Samsung Galaxy S6 / 6.0.1 - Application is crashing while creating lomotif on "Find Music" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1131]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START" and navigated to "Add Photos & Videos>>Albums" screen
3: Simultaneously tap on two folders from "Albums" tab, observed user will get "Folder" tile at the top of "Albums" folders list.
4: Navigate to "Facebook" folder and navigate to "Facebook" screen, observe the other assets are displayed under "Facebook" screen.
5: Select the assets and navigate to "Find music" before loading gets completed and "Facebook" assets get appeared under "Facebook" screen.
6: Tap on ">" option at top right corner of "Find Music" screen and wait for few secs.
7: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing while creating lomotif on "Find Music" screen.

**Note: Issue is observed when the user performs above steps as quick as possible.**

Defect debug details:
Device ID: a288cbfe-3346-49a3-9694-2857370c20d4R
ADID: c1cb06cb-b7d6-4d06-b280-d83045215e47
Auth Key: 716e2b3febc13e78f91844948ea5a7babdfc7a82

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3idncxaGIzMjVuWjQ

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
