### ISSUE TITLE
[2.0.6-r3 (127)] Moto X Play / 6.0.1 - "Notifications" are displayed under "Sign up/ Login" button on "Notification" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1132]
Frequency: Every time

Precondition:
- There should be some notifications under "Notification" screen.
- User should be logged in to the app.

Action:
1: Launch the app.
2: Navigate to "Notification" screen.
2: Navigate to "Profile>>Setting" screen and logged out from the app.
3: User will get "You are logged out" pop-up message, wait for few secs and tap on "Ok" option user will be then navigated to "Home" screen.
4: Navigate to "Notification" screen and refresh the screen.
5: Check if previously logged in user's "Notifications" are displayed under "Sign up/ Login" button or not.

Expected result: "Notifications" of previous logged in user should not be displayed under "Sign up/ Login" button on "Notification" screen.

Actual result: "Notifications" are displayed under "Sign up/ Login" button on "Notification" screen.

**Note: Previous logged in user notifications are displayed under other logged in user and recently logged in user notification is displayed when user navigate to "Home" screen and again navigate to "Notification" screen.**

Refer the following screenshot for more details:
![sign_login_button](https://cloud.githubusercontent.com/assets/24311318/23459690/8082edd0-fea7-11e6-8f12-066160e92490.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Google Pixel / 7.1.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
