### ISSUE TITLE
[2.0.6-r3 (127)] Samaung Galaxy S6 / 6.0.1 - Continuous loading sign is displayed under "Albums" tab when user refreshes the tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1137]
Frequency: Every time

Precondition:
- User should have newly installed app.

Action:
1: launch the app.
2: Tap on "START" and navigate to "Add Photos & Videos>>Albums" screen.
3: User will get "Access permission" pop-up message, tap on "DENY" option.
4: Refresh the "Albums" tab.
5: Check if continuous loading sign is displayed or not.

Expected result: Continuous loading sign should not display under "Albums" tab even when the user refreshes the tab.

Actual result: 
1: Continuous loading sign is displayed under "Albums" tab when the user refreshes the tab.
2: Loading sign is getting stuck when the user navigates to "Facebook/Instagram" folder and navigate back to "Albums" tab.

Note: User needs to navigate back to "Home" screen and again navigate to "Album" tab to get disappeared the loading sign.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iNTBmWjFrSHY3aFE

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r3 (127)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
