### ISSUE TITLE
[2.0.6-r4 (128)] Sony Xperia Z5 / 6.0.1 - Previous assets are displayed as selected on "Add Photos & Videos" screen even when user navigate back to "Home" screen.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1139]
Frequency: Every time

Action:
1: Launch app.
2: Tap on "START" and select some assets and navigate to "Create" screen with/without music.
3: Tap on "Home" icon and navigate back to "Home" screen.
4: Again tap on "START".
5: Check if previous selected assets displayed as selected or not.

Expected result: Previous assets should not be displayed as selected.

Actual result: 
1: Previous assets are displayed as selected.
2: User is able to proceed to "Create" screen without selecting assets again.

For more details refer following video link:
https://drive.google.com/open?id=0B2TfWRODMVhYZ3lrckhQRUQ0aGs

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
