### ISSUE TITLE
[2.0.6-r4 (128)] Moto X Play / 6.0.1 -Application is crashing when the user taps on "X" option and then immediately tap on "Retry" option of "Lomotif Upload failed" message.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1140]
Frequency: Every time

Action:
1: launch the app and login with a valid credential.
2: Tap on "START" and create lomotif with few motifs.
3: Proceed to "Create" screen with/without music and tap on export option.
4: After exporting completed, skip sharing and navigate to "Following" tab.
5: Turn on the offline mode, there will be no internet connection and observe uploading will get failed.
6: Navigate to "In Progress" tab and observe "Upload failed" message is displayed on "Lomotif" Thumbnail.
7: Tap on "X" option and then immediately tap on "Retry" option, the user will be navigated to "Create" screen.
8: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when the user taps on "X" option and then immediately tap on "Retry" option of "Lomotif Upload failed" message.

Defect debug details:
Device ID: 5e87a2b2-8745-45e6-9e26-582fa0557d93R
ADID: 0731a193-68c7-4d86-9791-d2ff1376d5d9
Auth Key: e1196d7569fb5cd89aceba30426881c0ecc114e7

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSENZajdjTkpldlk

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Samsung Galaxy S4 / 5.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
