### ISSUE TITLE
[2.0.6-r4 (128)] Moto X Play / 6.0.1 - "Uploading Lomotif" progress is displayed under "Following" tab even when user has logged out from the app.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1141]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START", create lomotif with few motifs and proceed to "Create" screen with/without music.
3: Tap on export option, after exporting completed skip sharing and navigate to "Following" tab.
4: Observe "Lomotif uploading" progress will be displayed at top of the screen.
5: Navigate to "Profile>>Setting" screen and log out from the app(As the application is crashing immediately after logging out from the app so wait for few secs before tapping on "Ok" option of pop-up: "Logged out..You have logged out" message).
6: Navigate back to "Following" tab.
7: Check if "Uploading Lomotif" progress is displayed or not.

Expected result:
1: "Uploading Lomotif" progress should not display under "Following" tab when the user has logged out from the app.
2: User should get a pop-up: "Do you want to cancel the uploading" message while logging out from the app.

Actual result: 
1: "Uploading Lomotif" progress is displayed under "Following" tab even when user has logged out from the app.
2: Uploading is in progress even after logged out from the app but after few secs upload failed is displayed.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ieXBpYUtxS3ZXNDg

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
