### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy Note 4 / 6.0.1 - "Lomotif upload failed" message on lomotif thumbnail is not displayed under "In Progress" tab  even when lomotif upload gets failed.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1142]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Create lomotif with Photos/Videos/Motif with/without music.
3: Navigate to "Create" screen and turn OFF the internet connection.
4: Export the lomotif and tap on "Make lomotif" button.
5: Turn ON the internet connection and tap on "I'm done. Thanks!".
6: Navigate to "In Progress" tab.
7: Check if "Lomotif upload failed" message on lomotif thumbnail is displayed or not.

Expected result: "Lomotif upload failed" message on lomotif thumbnail should be displayed under "In Progress" tab whenever lomotif upload gets failed.

Actual result: "Lomotif upload failed" message on lomotif thumbnail is not displayed under "In Progress" tab even when lomotif upload gets failed.

Please refer below video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudUk5ZNWstUkZpX1E

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Samsung Galaxy S4 / 5.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
