### ISSUE TITLE
[2.0.6-r4 (128)] Moto X Play / 6.0.1 - Continuous notifications(Notification sound also) are displayed for uploading process under "Device notification" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1143]
Frequency: Random

Precondition:
- There should be some lomotifs under "In progress" tab.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>In progress" tab and load one lomotif.
3: Export the lomotif, after exporting gets completed skip sharing and navigate to "Following" tab.
4: Turn on the offline mode, there be will be no internet and observe the upload will get failed.
5: Navigate to "In progress" tab and turn off the offline mode, there will be an internet connection.
6: Load the recently exported lomotif(In step 2) and export the lomotif.
7: After exporting gets completed, skip sharing and navigate to "Following" tab.
8: Check if the continuous notifications are displayed for uploading process or not.

Expected result: Continuous notifications should not display for uploading process.

Actual result: 
1: Continuous notifications are displayed for uploading process under "Device notification" screen.
2: Notifications are getting for every increase in progress under "Following" tab.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iNGxkRHhzSC1pQVk

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Samsung Galaxy S4 / 5.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
