### ISSUE TITLE
[2.0.6-r4 (128)] Google Pixel / 7.1.1 - "Lomotif uploaded" message is displayed on "Lomotif uploading progress" under "Following" tab.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1145]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create lomotif with Photos/Videos/Motifs with/without music and export.
3: Let the lomotif successfully uploaded.
4: Navigate to "Following" tab and observe "Lomotif uploaded" message will be displayed.
5: Tap on "Home" icon and tap on "START".
6: Create lomotif with Photos/Videos/Motifs with/without music and export.
7: Tap on "I'm done Thanks!" on "Share" screen and navigate to "Following" tab.
8: Check if "Lomotif uploaded" message is displayed on "Lomotif uploading progress" or not.

Expected result: "Lomotif uploaded" message should get disappear when uploading of other lomotif is in progress under "Following" tab.

Actual result:  "Lomotif uploaded" message is displayed on "Lomotif uploading progress" under "Following" tab.

Please refer attached screenshot for more details:
![21](https://cloud.githubusercontent.com/assets/24449093/23539766/6a7e506c-0003-11e7-8647-d4cf043de29f.jpg)

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
