### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy S6 / 6.0.1 - Comment/Like counts are getting reset to zero after refreshing the "Following" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1147]
Frequency: Every time

Precondition:
- There should be some lomotifs under "Following" tab.

Action:
1: launch the app and login with a valid credential.
2: Navigate to "Following"  tab and select the first lomotif observe comment count is zero.
3: Navigate to "Comments" screen and post one comment.
4: Navigate back to "Following" tab and observe the comment count is increased by 1.
5: Refresh the tab and after refreshing get completed.
6: Check if the comment count is getting reset to zero or not.

Expected result: Comment count should not get reset to zero after refreshing the "Following" tab.

Actual result: 
1: Comment/Like counts are getting reset to zero after refreshing the "Following" tab.
2: Comment/Like counts are displayed correctly after user refreshes the tab again.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iZS16YjQ3MDc1cUU

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Sony Xperia  Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved in test apk 2.0.6

**Comment by Aboli-Testershub** [comment]
@xiuie,Verified Fix.
