### ISSUE TITLE
[2.0.6-r4 (128)] Google Pixel / 7.1.1 - User is not navigating to recently uploaded lomotif after tapping on "Lomotif uploaded" message under "Following" tab

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1148]
Frequency: Every time

Precondition: There should be more than 2 lomotifs under "Following" tab.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START".
3: Create lomotif with Photos/Videos/Motifs with/without music.
4: Export lomotif and tap on "Make Lomotif" button.
5: Navigate to "Share" screen and tap on "I'm done. Thanks!".
6: Navigate to "Following" tab and scroll down upto 2 lomotifs.
7: Wait till lomotif gets uploaded and "Lomotif uploaded" message will after lomotif gets upload.
8: Tap on "Lomotif uploaded" message.
9: Check if user is navigating to recently uploaded lomotif or not.

Expected result: User should navigate to recently uploaded lomotif after tapping on "Lomotif uploaded" message under "Following" tab.

Actual result: User is navigating to above lomotif from current lomotif instead of recently uploaded lomotif after tapping on "Lomotif uploaded" message under "Following" tab.

Please refer below video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudSkJYY2o1RHB5bWs

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
