### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy S6 / 6.0.1 - Music from "Find Music" is audible on "Add Photos & Videos" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1151]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START", create lomotif with few motif and navigate to "Find Music" screen.
3: Select one song(Song should not be already loaded) and observe loading process will be displayed.
4: Tap on "<" option and navigate back to "Add Photos & Videos" screen.
5: Wait for few secs till the song gets load completely and after loading gets completed.
6: Check if Music from "Find Music" is audible on "Add Photos & Videos" screen.

Expected result: Music from "Find Music" is audible on "Add Photos & Videos" screen.

Actual result: 
1: Music from "Find Music" is audible on "Add Photos & Videos" screen.
2: Music is audible on others screen and also audible when user minimizes the app.

Note: Music stops playing when user kills the app.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iclJicTNfRkgzaWM

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
