### ISSUE TITLE
[2.0.6-r4 (128)] Moto X Play / 6.0.1 - "Oops something went wrong" message is displayed when user tries to change the "Profile info" on "Setting" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1152]
Frequency: Random

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>Setting" screen and navigate to "Username" screen.
3: Change the "Username" and tap on "Tick" option.
4: Check if  "Oops something went wrong" message is displayed or not.

Expected result: 
1: "Oops something went wrong" message is displayed when the user tries to change the "Profile info".
2: User should able to change the "Profile info" without any error.

Actual result: "Oops something went wrong" message is displayed when the user tries to change the "Profile info" on "Setting" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iaFdOMHNqSnZKQ001

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Pankaj-Testershub** [comment]
@xiuie, It is still reproduced for latest build [2.0.6-r5 (129)] on Moto X Pay / 6.0.1.
