### ISSUE TITLE
[2.0.6-r4 (128)] Nexus 5 / 6.0.1 - "Lomotif upload failed" message is not getting disappeared immediately after tapping on "x" on lomotif thumbnail under "In Progress" tab. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1153]
Frequency: Every time.

Precondition: There should at least one upload failed lomotif thumbnail under "In Progress" tab.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "User" icon and navigate to "In Progress" tab.
3: Tap on "x" option on upload failed lomotif thumbnail.
4: Check if "Lomotif upload failed" message is not getting disappeared immediately.

Expected result: "Lomotif upload failed" message should get disappeared immediately after tapping on "x" on lomotif thumbnail under "In Progress" tab.

Actual result: "Lomotif upload failed" message is not getting disappeared immediately after tapping on "x" on lomotif thumbnail under "In Progress" tab.

Please refer below video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudVFQ1VVZ0Y2tBME0

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Samsung Galaxy S4 / 50.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Pankaj-Testershub** [comment]
@xiuie Verified. Fixed.
