### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy S6 / 6.0.1 - User is not able to refresh the "Following" tab after deleting lomotif.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1154]
Frequency: Every time.

Precondition:
- There should be some own lomotifs under "Following" tab.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Following" tab and select own lomotif(First lomotif).
3: Tap on "Menu(...)" option and select "Delete" option.
4: Confirm delete by tapping on "Yes" option and after deleting process get completed, user can still see the lomotif.
5: Refresh the tab and immediately scroll down to other lomotif under "Following" tab(Observe refresh process is getting disappeared).
6: Scroll up to the first lomotif and try to refresh the tab.
7: Check if the user is able to refresh the "Following" tab or not.

Expected result: User should be able to refresh the "Following" tab after deleting lomotif.

Actual result: User is not able to refresh the "Following" tab after deleting lomotif.

Note: Similar issue is observed when user change lomotif privacy, unfollow any other user.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iWTJnN3dwdEdNb0E

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiu, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
