### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy J MAX /  5.1.1 - Continuous loading sign is displayed when user tap on "New notification" message under "Notification" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1155]
Frequency: Every time

Precondition:
- There should be some new "Like/Comment/Follow" notification under "Notification" screen.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Notification" screen, observe "New notification" message will be displayed at the top.
3: Refresh the screen and immediately tap on "New Notification" message and observe after refresh gets completed the "New notification" message displayed again.
4: Tap on "New notification" message.
5: Check if continuous loading sign is displayed or not.

Expected result: Continuous loading sign should not display when user tap on "New notification" message.

Actual result: 
1: Continuous loading sign is displayed when user tap on "New notification" message under "Notification" screen.
2: User is not able to tap again on "New notification" screen.
3: User needs to navigate to other screen and navigate back to "Notification" screen to get the refreshing completed.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iaVVmTi1oU25YR1E

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.0.6-r5 (129)] on Google Pixel / 7.1.1

**Comment by Pankaj-Testershub** [comment]
@xiuie, It is still reproduce on latest build [2.0.6-r5 (129)].
