### ISSUE TITLE
[2.0.6-r4 (128)] Samsung Galaxy S4 / 5.0.1 - Application is crashing when user continuous refresh the "Following" tab.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1157]
Frequency - Every time

Action:
1: Launch the app.
2: Tap on "START" and select more than 50 assets and navigate to create screen.
3: Export the lomotif and cancel sharing and navigate to "Following" tab.
4: Uploading process will displayed wait till uploading get completed.
5: After uploading get completed continuous refresh the "Following" tab.
6: Check if application is crashing or not.

Excepted Result: Application should not be crash when user continuous refresh the "Following" tab. 

Actual Result: Application is crashing when user continuous refresh the "Following" tab.

For more details refer following video link:
https://drive.google.com/open?id=0B2TfWRODMVhYWXJrcjFKN1k2cWs

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r4 (128)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved Android test build [2.0.6-r5 (129)]

**Comment by Aboli-Testershub** [comment]
@xiuie, It is still reproducible on latest build [2.0.6-r5 (129)] on Google Pixel / 7.1.1.
