### ISSUE TITLE
[2.0.6-r5 (129)] Moto X Play / 6.0.1 - "Access permission" pop-up is displayed even when user navigates to "In progress" tab from "Lomotifs" tab for the first time.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1160]
Frequency: Every time

Precondition:
- User should have newly installed app.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>In progress" screen, user will get "Access permission" pop-up and deny the access.
3: Navigate to "Lomotifs" tab and again navigate to "In progress" tab.
4: Check if the "Access permission" pop-up is displayed or not.

Expected result: "Access permission" pop-up should not display when the user navigates to "In progress" tab from "Lomotifs" tab for the first time.

Actual result: "Access permission" pop-up is displayed even when the user navigates to "In progress" tab from "Lomotifs" tab for the first time.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iMHhCRDc4Nlk1SmM

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r5 (129)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved in test apk 2.0.6

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fix.
