### ISSUE TITLE
[2.0.6-r5 (129)] Nexus 5 / 6.0.1 -"Album" tab is not displayed as highlighted even when user is in "Album" tab after swipe right to navigate "Album" tab from "Motifs" tab.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1161]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START" and navigate to "Add Photos & Videos" screen.
3: Tap on "Motif" tab and swipe right.
4: Check if album tab is displayed as highlighted or not.

Expected result: "Album" tab should be displayed as highlighted when the user is in "Album" tab.

Actual result: 
1: "Album" tab is not displayed as highlighted even when user is in "Album" tab.
2: It is working fine when user taps and navigate to "Album/Motifs" tab

Note:
1: Similar issue is observed for "Motifs" tab.
2: User is not able to swipe "Find Music" tab and "My Music" tab.
 
Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudNFF5eVd2ZG5OSGc

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r5 (129)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposedly resolved in test apk 2.0.6

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fix.
