### ISSUE TITLE
[2.0.6-r5 (129)] Samsung Galaxy Note 4 / 6.0.1 - Album heading is getting disappeared when user simultaneously taps on both "X" options on "Add & Photos Screen".

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1162]
Frequency - Every time

Action:
1: Launch the app.
2: Tap on "START" and open any folder from "Album" tab.
3: Select some assets from folder.
4: Simultaneously tap on both "x" options of folder name and album screen.
5: Observe blank screen is displayed, refresh the tab.
6: Check if folder heading is getting disappeared or not.

Excepted Result:  Album heading should not get disappeared when user simultaneously taps on both "X" options on "Add & Photos Screen".

Actual Result:  
1: Album heading is getting disappeared when user simultaneously taps on both "X" options on "Add & Photos Screen".
2: Blank screen is displayed when user simultaneously taps on "X" before refresh the tab.

For more details refer following video link:
https://drive.google.com/open?id=0B2TfWRODMVhYR1ZHYlI4VTl4MUk

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r5 (129)] on Samsung Galaxy S4 / 5.0.1

**Comment by xiuie** [comment]
Supposedly resolved in test apk 2.0.6

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fix.
