### ISSUE TITLE
[2.0.6-r5 (129)] Sony Xperia Z5 / 6.0.1 - Uploaded Lomotif is not getting properly aligned on "Following" tab.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1163]
Frequency - Every time

Precondition: There should be at least one lomotif uploaded. 

Action:
1: Launch the app.
2: Tap on "START" and select some assets, navigate to create screen with/without music. 
3: Tap on "Adjust" and select 16:9 view.
4: Tap on export and skip sharing, navigated to following screen.
5: Uploading process will displayed,when upload completed tap on "Lomotif Upload" pop up.
6: Check if lomotif is properly aligned or not.

Excepted Result: Uploaded Lomotif should be get properly aligned on "Following" tab.

Actual Result: Uploaded Lomotif is not getting properly aligned on "Following" tab.

For more details refer following screenshot:

![1163](https://cloud.githubusercontent.com/assets/25073306/23691090/74af1f48-03ec-11e7-97ee-16c807a8d866.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.6-r5(129)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposedly resolved in test apk 2.0.6

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fix.
