### ISSUE TITLE
[1.0.17] Dell Tab/ android 4.4.4- "User is unable to perform any task while  Loading Lomotif music".

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#117]
Action:

1.Launch Lomotif app.
2.Tap on start button.
3.select a video.
4.select any music file and try to perform any another task.
5.check whether you are able to perform any task or not while loading music.

Expected result: While loading video user should able to perform any other task also.

Actual result: User is unable to perform any task while  Loading Lomotif music.

![per1](https://cloud.githubusercontent.com/assets/12474351/14421691/a8c343be-fff0-11e5-9672-4882900b8868.png)

**Comment by xiuie** [comment]
@pmtheint The iOS has a skip button.. But maybe android already has a back button. Anyway fyi. :)
