### ISSUE TITLE
[1.0.17] Dell Tab/ android 4.4.4- "User is not able to select all the videos at a time".

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#118]
Action:
1.Launch Lomotif app.
2.Tap on start button.
3.select the videos.
4.check whether the user is able to select all the video at a time or not.

Expected result:User should able to select all the videos at a time.

Actual result: User is not able to select all the videos at a time.

**Comment by xiuie** [comment]
@vinay97t How many videos was this? You should be able to see the number selected on the top.
