### ISSUE TITLE
[2.0.9 (139)] Samsung Galaxy Note 4 / 6.0.1 - "LOMOTIF" text displayed on lomotif preview is truncated from right side when user share 16:9 view lomotif on "Instagram".

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1204]
Frequency: Every time

Precondition: Instagram app should be installed and logged in with valid credentials.

Action:
1: Launch the app with/without login.
2: Tap on "START" and create 16:9 lomotif with photos/videos/motifs with/without music.
3: Export and share lomotif on "Instagram".
4: Wait till lomotif get upload.
5: Check if "LOMOTIF" text displayed on lomotif preview is truncated

Expected result: "LOMOTIF" text displayed on lomotif preview should not be truncated from left when user share 16:9 view lomotif on "Instagram".

Actual result: "LOMOTIF" text displayed on lomotif preview is truncated from left when user share 16:9 view lomotif on "Instagram".

Please refer attached screenshot for more details:
![38](https://cloud.githubusercontent.com/assets/24449093/24697455/dadd4d38-1a0a-11e7-821b-bda34073c1e9.jpg)

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Sony Xperia Z5 / 6.0.1
