### ISSUE TITLE
[2.0.9 (139) Samsung Galaxy S6 / 6.0.1 - "Oops, this username is taken.Try..." message is displayed after tapping on "Tick" option without changing or entering existing username.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1206]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>Settings>>Username" screen.
3: Tap on "Tick" option at top right corner of the screen.
4: Check if "Oops, this username is taken.Try..." message is displayed or not.

Expected result: User should navigate to "Settings" screen after tapping on "Tick" option without changing or entering existing username.

Actual result: "Oops, this username is taken.Try..." message is displayed after tapping on "Tick" option without changing or entering existing username.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iX2dPMzlIeVN5MlE

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aishwarya-Testershub** [comment]
@xiuie, Verified Fixed.
