### ISSUE TITLE
[2.0.9 (139)] Sony Xperia / 6.0.1 - User fails to navigate "Check Your Mail" page after "Sign Up".

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1207]
Frequency - Every time

Action:
1: Launch the app.
2: Navigate to "Profile>>Sign Up" screen.
3: Enter all valid details and tap on "Sign Up" button.
4: Check if user fails to navigate "Check Your Mail" page after "Sign Up"

Excepted Result: User should be navigate "Check Your Mail" page after "Sign Up"

Actual Result: User fails to navigate "Check Your Mail" page after "Sign Up"

Refer following video link for more details:
https://drive.google.com/open?id=0B2TfWRODMVhYVTZNVV9Ib0hzbkU

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Moto X Play / 6.0.1

**Comment by xiuie** [comment]
We're skipping "Check your mail" page for upcoming versions on iOS and Android
