### ISSUE TITLE
[2.0.9 (139)] Moto X Play / 6.0.1 - Continuous loading is displayed when user taps multiple times on "Instagram" link option.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1208]
Frequency: Every time

Action:
1: Launch the application and login with a valid credential.
2: Navigate to "Profile>>Settings" screen.
3: Tap on "Instagram" link option for multiple times.
4: Check if continuous loading is displayed or not.

Expected result: Continuous loading should not display when user taps multiple times on "Instagram" link option.

Actual result: Continuous loading is displayed when user taps multiple times on "Instagram" link option.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iel9mQXNPbUZlODg

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Sony Xperia Z5 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
