### ISSUE TITLE
[2.0.9 (139)] Google Pixel / 7.1.1 - Irrelevant message as "This lomotif account is already associated..." is displayed when user tries to link facebook account in offline mode. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1215]
Frequency: Every time

Precondition: Facebook account should be unlink and should not link with any other lomotif account.

Action: 
1: Launch the app and login with valid credentials.
2: Tap on "User" icon and navigate to "Profile>>Settings" screen.
3: Turn OFF internet connection.
4: Tap on "Facebook" option.
5: Check if irrelevant message as "This lomotif account is already associated..." is displayed.

Expected result: Relevant error message as "No Internet Connection" should be displayed when user try to link with facebook account in offline mode.

Irrelevant message as "This lomotif account is already associated..." is displayed when user tries to link facebook account in offline mode. 

**Note: Similar issue is observed on "Add Photos & Videos" screen.**

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudSUZFREVIalhTRm8

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Sony Xperia Z5 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Google Pixel / 7.1.1

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aishwarya-Testershub** [comment]
@xiuie, Verified Fixed.
