### ISSUE TITLE
[2.0.9 (139)] Sony Xperia / 6.0.1 - Irrelevant warning message as "Our server is little busy.." is displayed when user try Sign up/ Login in offline mode. 

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1216]
Frequency - Every time

Precondition - Turn off the internet connection.

Action:
1: Launch the app.
2: Navigate to "Profile>>Sign Up/Log In" screen.
3: Enter all valid details and tap on "Sign Up/Log in" button.
4: Check if Irrelevant warning message as "Our server is little busy.." is displayed.

Excepted Result: Relevant warning message should be displayed when user try Sign up/ Login in offline mode.

Actual Result: Irrelevant warning message as "Our server is little busy.." is displayed when user try Sign up/ Login in offline mode. 

Refer screenshot for more details:

![096](https://cloud.githubusercontent.com/assets/25073306/24752928/ab61dfcc-1aed-11e7-81ad-d9b09dbf62a5.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9 (139)] on Google Pixel / 7.1.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aishwarya-Testershub** [comment]
@xiuie, Verified Fixed.
