### ISSUE TITLE
[2.0.9-r1 (140)] Samsung Galaxy Note 4 / 6.0.1 - Irrelevant message: "This Lomotif account is already associated with..." is displayed when user tries to invite friends via "Facebook" account.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1220]
Frequency: Every time

Precondition:
- User should not be linked with facebook account.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>Settings" screen.
3: Tap on "Invite Friends" option and login with valid facebook credential.
4: Check if Irrelevant message: "This Lomotif account is already associated with..." is displayed when user tries to invite friends via "Facebook" account.

Expected result: Irrelevant message: Irrelevant message: "This Lomotif account is already associated with..." should not be displayed when user tries to invite friends via "Facebook" account.

Actual result: 
- Irrelevant message: "This Lomotif account is already associated with..." is displayed when user tries to invite friends via "Facebook" account.
- Facebook is displayed as linked with lomotif account.

Note: Issue is specifically observed when user logged in the app.

Refer following video lin for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ieGpGVUo2c3V3azQ

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by jpaulo1205** [comment]
@Pankaj-Testershub 

- just to confirm, is the Lomotif account in the device not linked with any Facebook account? 
- is the Facebook account used when invite friends is tapped not linked to any Lomotif account?

**Comment by Pankaj-Testershub** [comment]
@jpaulo1205 
- No Lomotif account is not linked with any "Facebook" account.
- No "Facebook" account is not linked with any other Lomotif account.

**Comment by xiuie** [comment]
Supposed fixed in  2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
