### ISSUE TITLE
[2.0.9-r1 (140)] Samsung Galaxy Note 4 / 6.0.1 - Continuous loading is displayed when user simultaneously taps on "Login" and "Log in with Facebook" buttons.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1221]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Profile>>Sign up/Login" screen.
3: Tap on "Login" option.
4: Simultaneously tap on "Login" and "Login with Facebook" buttons, observe user will get "Username can only contain alphanumeric.." message.
5: After few secs, user will be navigated to "Facebook" login screen.
6: Tap on "Back" button(Device hard key) and navigate to "Login" screen.
7: "Login Failed" message will be displayed, tap on "Ok" and tap on "Ok" on "Username can only contain.." message.
8: Check if continuous loading is displayed or not.

Expected result: Continuous loading should not be displayed when user simultaneously taps on "Login" and "Login with Facebook" buttons.

Actual result: Continuous loading is displayed when user simultaneously taps on "Login" and "Login with Facebook" buttons.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iZk1jbjBibl9BMm8

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in  2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
