### ISSUE TITLE
[2.0.9-r1 (140)] Samsung Galaxy Note 4 / 6.0.1 - "Oops, something went wrong.." message is displayed when user cancels the inviting friends via "Facebook" and navigate back to "Settings" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#1222]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile>>Settings" screen.
3: Tap on "Invite Friends" option and user will be navigated to "Facebook" login screen.
4: Cancel inviting friends by tapping on "Back" button(Device hard key) and navigate back to "Settings" screen.
5: Check if  "Oops, something went wrong.." message is displayed or not.

Expected result: "Oops, something went wrong.." message should not be displayed when user cancels inviting friends via "Facebook" and navigate back to "Settings" screen.

Actual result: "Oops, something went wrong.." message is displayed when user cancels inviting friends via "Facebook" and navigate back to "Settings" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iRzQtTkRIcnNDX2c

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Nexus 5 / 6.0.1

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
