### ISSUE TITLE
[2.0.9-r1 (140)] Samsung Galaxy S6 / 6.0.1 - User is navigating to Album screen instead of exiting from the app when user taps on "back" key (device hard key) on Home screen.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-android-issues#1223]
Frequency: Every time

Action:
1: Launch app.
2: Tap on "START" and select some assets and navigate to "Create" screen with/without music.
3: Tap on "Home" option, Navigate back to "Home" screen.
4: Tap on "back" key (device hard key).
5: Check if user is navigating to Album screen instead of exiting from the app.

Excepted Result: User should be exit from the app when user taps on "back" key (device hard key) on Home screen.

Actual Result: User is navigating to Album screen instead of exiting from the app when user taps on "back" key (device hard key) on Home screen.

Refer video link for more details:
https://drive.google.com/open?id=0B2TfWRODMVhYM3gwVWd3TnRQZEE

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S4 / 5.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aishwarya-Testershub** [comment]
@xiuie Verified fixed.
