### ISSUE TITLE
[2.0.9-r1 (140)] Google Pixel / 7.1.1 - Irrelevant warning message as "Oop's Something wrong..." is displayed when user taps on "Connect with Facebook" button in offline mode.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1224]
Frequency: Every time

Precondition: Turn ON Airplane mode

Action:
1: Launch the app.
2: Tap on "User" icon and navigate to "Sign up | Log in" screen.
3: Tap on "Connect with Facebook" button.
4: Check if the irrelevant warning message is displayed.

Expected result: Relevant warning message as "No internet connection" should be displayed when user taps on "Connect with Facebook" button in offline 

Actual result: Irrelevant warning message as "Oop's Something wrong..." is displayed when user taps on "Connect with Facebook" button in offline mode.

Please refer attached screenshot for more details:
![41](https://cloud.githubusercontent.com/assets/24449093/24796021/022ab0f2-1ba9-11e7-9287-90a5a88ff909.jpg)

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
