### ISSUE TITLE
[2.0.9-r1 (140)] Google Pixel / 7.1.1 - "Password" field is displayed as filled and also "Current Password" field is available on "Password" screen when user has signed up with Facebook account.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1225]
Frequency: Every time

Action: 
1: Launch the app and Sign up with Facebook.
2: Tap on "OK" on confirm login pop up.
3: Navigate to "Set Username" screen.
4: Set the username and navigate to "Profile" screen.
5: Check if password field is displayed as filled and also "Current password" field is available.

Expected result: "Password" field should be displayed blank with a red warning symbol and "Current Password" field should not be available on "Password" screen when user has signed up with Facebook account.

Actual result: "Password" field is displayed as filled and also "Current Password" field is available on "Password" screen when user has signed up with facebook account.

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudUXdqanJ2V1JQcDg

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Nexus 5 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
