### ISSUE TITLE
[2.0.9-r1 (140)] Google Pixel / 7.1.1 - No warning message is displayed when user tries to unlink Facebook account in offline mode.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#1226]
Frequency: Every time

Precondition: Facebook account should be linked.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "User" icon and navigate to "Profile>>Settings" screen.
3: Turn OFF internet connection.
4: Tap on "Facebook" option(Unlink pop up will appear).
5: Select "Unlink" option.
6: Check if any warning message is displayed.

Expected result: Relevant warning message as "No internet connection" should be displayed when user tries to unlink facebook account is offline.

Actual result: No warning message is displayed when user tries to unlink facebook account in offline mode.

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.9-r1 (140)] on Samsung Galaxy S6 / 6.0.1

**Comment by xiuie** [comment]
Supposed fixed in 2.0.9-r2 (build 141)

**Comment by Aboli-Testershub** [comment]
@xiuie, Verified Fixed.
