### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Instagram and Facebook Folder Bug - At My Video screen, Instagram and Facebook button not working

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#13]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Click on Either Instagram or Facebook folder to select photos

Expected result: Clicked folder (Instagram / Facebook) should be opened

Actual result: Instagram and Facebook folder clicking not working

**Comment by xiuie** [comment]
What are the launch features for Android? If Instagram and Facebook import feature will not be in the launch build, please close this issue.

**Comment by Dipamit** [comment]
I am able to reproduce this issue on Motorola Nexus 6 with Android 6.0.1

**Comment by kcherkas** [comment]
Issue reproducible on samsung galaxy S4, android 4.4.2 build v 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @paulyangzhiwen I can still reproduce this issue for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1

**Comment by jpaulo1205** [comment]
Note: Facebook/Instagram not yet fully integrated. Removed the folders temporarily

Fixed in 1.0.15
