### ISSUE TITLE
[1.0.18] Samsung Galaxy Grand Prime/5.0.2 - Music not repeated if the selected Audio clip is less than 30 sec (or 15 sec) 

### ISSUE THREAD

**Issue by archanaoswal** [Lomotif/lomotif-android-issues#132]
[1.0.18] Music not repeated if the selected Audio clip is less than 30 sec (or 15 sec) 

Frequency: Every Time

Action:
1. Launch Lomotif
2. Click on start
3. Select few images
4. In the Find music screen, select a music file that is less than 15 sec long
5. Create the Lomotif
6. After the Audio file is finished playing once, the remaining video is silent

Expected Result: The music should be started all over again

Actual Result: After the Audio file is finished playing once, the remaining video is silent

**Comment by xiuie** [comment]
@archanaoswal You added a music file from your own library on from our library? I think this works as designed.

**Comment by archanaoswal** [comment]
@xiuie: I added a music from my own library. It was a suggestion, more than a defect as part of the video goes silent

**Comment by pmtheint** [comment]
Ok I'll mark this as improvement
