### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Search tab Bug - At My Video screen, Search tab not working

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#14]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Observe available folders for photos at My Video tab
4. Click on search tab
5. Search for "Facebook" word or any other word

Expected result: Searched folder / photos / videos should be display as results

Actual result: No result display, search tab not working

![1](https://cloud.githubusercontent.com/assets/9691390/13839627/72b16aba-ec42-11e5-91cf-8cd6f00f612a.png)

![2](https://cloud.githubusercontent.com/assets/9691390/13839626/72aaeb04-ec42-11e5-91a0-0b303ef3527d.png)

**Comment by xiuie** [comment]
@benchang I think "Search Motifs" is currently turned off for Android? If so, please close this issue. Thanks.

**Comment by hiteshbheda** [comment]
@xiuie @benchang I can't replicate this issue now for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1

In fact, i was misinterpreting at that time. I thought that it should search from available folder as there were no motif category.

Now, all confusion clear from my end. Thanks @xiuie ..!!!
