### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Filter button Bug - Filter button does not make any effect on lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#15]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select photos from Camera folder from My Video tab
4. Select any song from Find Music tab
5. Now, Click on Filter button and male it ON
6. Observe playing lomotif

Expected result: Filter effect should be applied on lomotif

Actual result: When doing Filter value ON, it does not affect on the playing lomotif screen

**Comment by xiuie** [comment]
Sorry! Forgot to mention current version does not have filters
