### ISSUE TITLE
[1.0.19] Samsung Galaxy Grand Prime/5.0.2 - Application crashes after exporting any Lomotif

### ISSUE THREAD

**Issue by archanaoswal** [Lomotif/lomotif-android-issues#157]
[1.0.19] Samsung Galaxy Grand Prime/5.0.2 - Application crashes after exporting any Lomotif

Frequency: Every Time

Action:
1. Launch Lomotif
2. Select an existing Lomotif or create a new one and let it load
3. Click on export
4. Application crashes

Expected Result: The lomotif should be exported

Actual Result: Application crashes

**Comment by jpaulo1205** [comment]
@archanaoswal hi, I've uploaded another build version 1.0.19.1, can you check if the export crash still occur on your device on that build. thanks

**Comment by archanaoswal** [comment]
@jpaulo1205 I have updated to the new version and now I am able to export. Thanks
