### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Unable to scroll up - During creating lomotif, once reached at bottom at song waves then unable to scroll up

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#16]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 photos from Camera folder from My Video tab
4. Select any song from Find Music
5. Now, scroll down the screen and go at the bottom
6. Again try to scroll up

Expected result: Screen should ne scrolled up

Actual result: Unable to go up by scroll up the screen

![screenshot_2016-03-15-23-10-25](https://cloud.githubusercontent.com/assets/9691390/13840667/d7ac460e-ec49-11e5-936a-0a0f64a358b3.png)

**Comment by jpaulo1205** [comment]
it is working as intended (when waveform is in focus, it can only be scrolled left to right and vice versa)

as a fix, added some space above the waveform to allow scroll up/down

Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@jpaulo1205 Thanks.!! But once user reached to bottom, he/she should go in up direction to check or play lomotif.

But if it works as design then it's fine.

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this now for build version [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1
