### ISSUE TITLE
[1.0.19] Samsung Galaxy Grand Prime/5.0.2 - Difference in height of lomotif preview section when you select "instagram - 15 sec" and "Lomotif - 30 sec"

### ISSUE THREAD

**Issue by archanaoswal** [Lomotif/lomotif-android-issues#160]
[1.0.19] Samsung Galaxy Grand Prime/5.0.2 - Difference in height of lomotif preview section when you select "instagram - 15 sec" and "Lomotif - 30 sec"

Frequency: Every Time

Action:
1. Launch Lomotif
2. Click on Start
3. Select a few images
4. On the "Add Music" page make sure no music file is selected
5. On create screen "Instagram - 15 sec" is selected by default and whole screen is used
6. Now select "Lomotif - 30 sec"
7. There is a blank space at the bottom and the Lomotif Preview section height is reduced

Expected Result: For both the options, the height of the Lomotif should be same

Actual Result: There is a blank space at the bottom and the Lomotif Preview section height is reduced

![screenshot_2016-04-29-06-56-38 1](https://cloud.githubusercontent.com/assets/18290603/14906352/1dcf0fa4-0dd8-11e6-9a95-233da16148c6.png)
![screenshot_2016-04-29-06-56-32 1](https://cloud.githubusercontent.com/assets/18290603/14906355/28bde5b6-0dd8-11e6-868a-1edae9d22cd8.png)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1

**Comment by xiuie** [comment]
@archanaoswal Instagram outputs as a square format and Lomotif is Landscape. Works as designed.

**Comment by hiteshbheda** [comment]
@xiuie Agree with you Xiu
