### ISSUE TITLE
[1.0.19] Samsung Galaxy S4/5.0.1 - keyboard not hiding after export via email

### ISSUE THREAD

**Issue by ukrpas** [Lomotif/lomotif-android-issues#163]
Freq: every time
Steps:
1. Launch the app
2. Select any video
3. Add music
4. Export clip via email (i use standart Gmail app for Android)
5. Send email
Act: keyboard not hiding after email was sent (see screenshot)
Exp: keyboard hiding
![screenshot_2016-04-29-10-32-39](https://cloud.githubusercontent.com/assets/11840791/14910465/333d1c78-0df6-11e6-8006-850ba424423c.png)

**Comment by testershub** [comment]
Please see same issue is reproducible for me as well on Samsung Galaxy Tab S2/ 5.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1

**Comment by vysohanych** [comment]
I can reproduce it on build 1.0.19.1 on Asus Nexus 7 Android 5.1.1.

**Comment by xiuie** [comment]
I have logged #174 Thanks!
