### ISSUE TITLE
[1.0.19.1] Samsung Galaxy Grand Prime/5.0.2 - Each time you export the same Lomotif (without even making changes), a new video file is created in the gallery (file system)

### ISSUE THREAD

**Issue by archanaoswal** [Lomotif/lomotif-android-issues#167]
[1.0.19.1] Samsung Galaxy Grand Prime/5.0.2 - Each time you export the same Lomotif (without even making changes), a new video file is created in the gallery (file system)

Frequency: Every Time

Action:
1. Launch Lomotif
2. Create a Lomotif
3. Click on Export
4. The lomotif is saved in the folder "lomotif-staging"
5. Now open the Lomotif again
6. Again Export
7. Another copy of the same lomotif is created in this folder

Expected Result: A new video file should not be created

Actual Result: Another copy of the same lomotif is created in this folder

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1
