### ISSUE TITLE
[1.0.19.1] Samsung Galaxy S4/5.0.1, Samsung Galaxy Note4/5.0.1 - No motifs under the search term '#mcm' when user opens #mcm folder.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#171]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Tap on the search field on Add Photos & Videos screen
4. Open the #mcm folder and check if there are any motifs in that folder.

Expected result: User should see at least one motif in the folder.

Actual result: There are no motifs in #mcm folder.

**Comment by testershub** [comment]
![mcm](https://cloud.githubusercontent.com/assets/18608449/14933996/680c1822-0ebf-11e6-8519-2b51d8a3f04e.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1

Similar to #170 . I think it's because of database items
