### ISSUE TITLE
[1.0.19.1] Samsung Galaxy S4/5.0.1, Samsung Galaxy Note4/5.0.1 - Videos in "moutain" folder are getting disappeared when user scrolls in the folder till the bottom.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#178]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Tap on the search field and search "moutain" folder on Add Photos & Videos screen
4. Scroll down till the bottom and check if videos in the folder are getting disappeared.

Expected result: Videos in the folder should not get disappeared when user scrolls down till the bottom.

Actual result: Videos are getting disappeared when user scrolls down till the bottom.

Note:
Refer the following video link for more information:
http://www.screencast.com/t/5NeliFUz

**Comment by hiteshbheda** [comment]
@xiuie Similar to #175
