### ISSUE TITLE
[1.0.13] Samsung Galaxy Tab S 10.5 / Android 4.4.2 - Settings - Keyboard doesn't disappear when user sends a feedback

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#18]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap Settings icom
3. Tap Send Feedback button
4. Use Gmail application for feedback
6. Rotate device to landscape mode
7. Enter feedback and send it

Expected result: User sees Settings screen without keyboard

Actual result: User sees Settings screen with opened keyboard

Video: [Recording.zip](https://github.com/Lomotif/lomotif-android-issues/files/177584/Recording.zip)

**Comment by xiuie** [comment]
Does it dismiss once you tap something else @vysohanych ?

**Comment by vysohanych** [comment]
Keyboard disappears when user taps physical back button on device

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by vysohanych** [comment]
@xiuie @jpaulo1205 I can't reproduce it on build 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce it now for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1.
