### ISSUE TITLE
[1.0.13] Samsung Galaxy Tab S 10.5 / Android 4.4.2 - All Application - Not user friendly font's color in all application

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#19]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open different screens

Expected result: More user friendly font's color in all application

Actual result: Not user friendly font's color in all application

![screenshot_2016-03-17-11-36-23](https://cloud.githubusercontent.com/assets/3593359/13842379/81b007b2-ec36-11e5-8553-e282331c3908.png)
![screenshot_2016-03-17-11-36-30](https://cloud.githubusercontent.com/assets/3593359/13842380/81b07d5a-ec36-11e5-848f-09500e7b03e3.png)

**Comment by Dipamit** [comment]
I am able to reproduce this issue on Motorola Nexus 6 with Android 6.0.1

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 This is has been resolved in build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1

Design is comparatively better now than previous build version.

![screenshot_2016-04-04-21-05-08](https://cloud.githubusercontent.com/assets/9691390/14253501/5e1a2522-faa9-11e5-92c1-330792058fa0.png)
