### ISSUE TITLE
[1.1.1 (20)] Asus Zenfone Go 4.5 / Android 5.1 - Loading never ending - Open any existing lomotif created on build [1.0.19.1] or earlier version

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#192]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open any existing lomotif created on build [1.0.19.1] or earlier version
3. Check whether lomotif opens or not 

Expected result: Selected lomotif should be opened

Actual result: Lomotif is not opening - Its continue loading

**Comment by Dipamit** [comment]
Not able to reproduce this issue on Xiaomi Redmi Note 3/5.1.1 for build [1.1.1(20)]

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.1.2(21) on Asus Nexus 7 Android 5.1.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build 1.1.2 [22] on Asus Zenfone Go 4.5 / Android 5.1
