### ISSUE TITLE
[1.1.1 (20)] Asus Zenfone Go 4.5 / Android 5.1 - App logo not working - Click or Tap on Lomotif App logo on Application Home screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#193]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Home / Start screen will display
3. Click / Tap on Application Logo to capture picture
4. Check whether click or tap on logo capture the picture or video or not

Expected result: Clicking / Tapping on App logo should capture image / video as working in iOS app

Actual result: Clicking / Tapping on Logo does not make any effect

**Comment by Dipamit** [comment]
Able to reproduce this issue on Xiaomi Redmi Note 3 /5.1.1 for build [1.1.1(20)]

**Comment by xiuie** [comment]
Feature has not been developed yet.
