### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Back Button Bug on Photo selection screen - While selecting photos and try to go back at My Video tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#2]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 photos from Camera folder from My Video tab
4. Click on Back button to go back at home screen

Expected result: It should redirect us to previous screen / home screen

Actual result: Back button does not work

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by vysohanych** [comment]
@xiuie @jpaulo1205 Can't reproduce on build 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this issue on build [1.0.14] with Sony xPeria Z / Android 5.1.1
