### ISSUE TITLE
[1.0.13] Samsung Galaxy Tab S 10.5 / Android 4.4.2 - Home screen - The application crashes when user tries to open two lomotifs at the same time

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#20]
Frequency: Some Time

Action:
1. Launch Lomotif
2. Try open two lomotifs at the same time

Expected result: Only one lomif is opened

Actual result: The application crashes

Video: [Recording.zip](https://github.com/Lomotif/lomotif-android-issues/files/177671/Recording.zip)

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can replicate it every time on Sony xPeria Z / Android 5.1.1.

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't replicate it now on build [1.0.14] with Sony xPeria Z / Android 5.1.1
