### ISSUE TITLE
[1.1.2(22)] Samsung Galaxy Note 4/6.0.1, Samsung Galaxy S4/5.0.1- Thumbnails are not displayed on "Add Photos & Videos" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#206]
Frequency: Every time.

Action: 
1. Launch the application. 
2. Tap on "Start" button.
3. Check if thumbnails are displayed on "Album" and "Motif" tab.

Expected result: Thumbnails of the folders should be displayed on "Add Photos & Videos" screen.

Actual result: Thumbnails are not displayed.

Refer screenshot for more information.

**Comment by testershub** [comment]
![thumbnail](https://cloud.githubusercontent.com/assets/18608449/16108426/a446b1dc-33c0-11e6-9dd9-496ca9c6f198.jpg)

**Comment by vysohanych** [comment]
It's duplicate of #173
