### ISSUE TITLE
[1.0.13] Motorola Nexus 6/ Marshmallow 6.0.1 -Create- Unable to see text box when keypad is open.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#21]
Frequency : Every time

Action:
1. Open created Lomotif video or create new.
2. scroll down and try to enter text in "Enter Title".

Expected result: Title should Able to see  while keypad is open.

Actual result: Unable to see text box when keypad is open.
![screenshot_20160317-162600](https://cloud.githubusercontent.com/assets/17335200/13844330/306990ca-ec5f-11e5-8e9d-65c5d19a74f9.png)

**Comment by xiuie** [comment]
@pmtheint This works like the iOS one.. No feedback while typing.

**Comment by Dipamit** [comment]
This is not work as designed I think. When you tap on Title on Android, it hide the text box behind the Keypad, by which user can't check what he/she is typing. Where as in IOS when you tap on Title text box, it will open keypad but it showing Title text box top of the keypad by which user can see what he/she is typing. This should be resolved.

**Comment by pmtheint** [comment]
Interesting. That's more on platform limitation because the built-in keyboard is too large. Will figure out a work around.

**Comment by hiteshbheda** [comment]
@xiuie @pmtheint I can't able to see "Enter Text" box for build [1.0.14] on Sony xPeria Z / Android 5.1.1.

But I agree with @pmtheint as there is longer keyboard in android compared to iOS app

**Comment by jpaulo1205** [comment]
Will close this one for the meantime as the Title feature is not yet fully integrated and was removed
