### ISSUE TITLE
Connectivity problems

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-android-issues#231]
Window with the message "Oops, the connectivity is a little flaky. Make sure you're connected to Wi-Fi or Data" is popping up all the time when making the videoclip. 

Steps to reproduce:
1. Open Lomotif Application
2. Click "Start" button
3. Enter into the Search field any search word  (For Ex. "Flowers")
4. Click next ">"

Expected result: No such message is popping up, application should handle reconnection problems without involving user all the time.

Device: Samsung Galaxy S5
Version: 5.0
Service Provider: Sprint

Reported by Olga

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue on build 1.1.2(22) on Asus Zenfone Go 4.5 / Android 5.1
