### ISSUE TITLE
[1.2.0 (23)] Samsung Galaxy Tab S 10.5 / Android 4.4.2 - Find Music - Search with typo e.g. "Nickki minij" doesn't return results for "Nicki Minaj"

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#237]
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Switch to Motif tab on the Add Photo & Video screen
4. Select few motifs
5. Tap next button on Add Photo & Video screen
6. Search for "Nickki minijj" on Find Music screen

Expected result: Search with typo e.g. "Nickki minijj" returns results for "Nicki Minaj"

Actual result: Search with typo e.g. "Nickki minijj" doesn't return results for "Nicki Minaj"

![screenshot_2016-06-28-21-15-19](https://cloud.githubusercontent.com/assets/3593359/16416577/9b81ab76-3d4b-11e6-826d-380eb30adee5.png)

**Comment by xiuie** [comment]
Thanks for pointing this out. Will change regression test to one J.

**Comment by testershub** [comment]
I can reproduce this issue for build 1.3.0(25) on Samsung Galaxy S4 / 5.0.1.
Search with typo e.g. "Nickki minijj" doesn't return results for "Nicki Minaj".

**Comment by xiuie** [comment]
@testershub Try one "j" i.e. try "Nickki minij" instead of "Nickki minijj". We should have modified the regression testing checklist
