### ISSUE TITLE
[1.0.13] Asus Nexus 7 / Android 5.1.1 - My Video - Incorrect view of search text when user uses very long text

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#24]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Enter long search text on My Video screen

Expected result: User sees video on Create screen or user can't use very big files

Actual result: Search text can overlap back button on My Video screen. Also search text doesn't end with three dots.

Note: The same behavior on Find music screen

![screenshot_2016-03-18-01-27-29](https://cloud.githubusercontent.com/assets/3593359/13864368/96e69b6e-eca9-11e5-9c3f-11e08adb12bc.png)

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this now for build [1.0.14] on Sony xPeria Z / Android 5.1.1

It works correctly with 3 dots at the end of string to show some text is still there.
