### ISSUE TITLE
[1.2.0 (23)] Samsung Galaxy Tab S 10.5 / Android 4.4.2 - Create - Preview stops after playing about 5-th motif

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#241]
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Switch to Motif tab on the Add Photo & Video screen
4. Select 100 motifs
5. Tap next button on Add Photo & Video screen
6. Tap next button on the Find Music screen (no add song)

Expected result: Preview plays smoothly

Actual result: Preview stops after playing about 5-th motif

Video: [Recording #256.zip](https://github.com/Lomotif/lomotif-android-issues/files/337392/Recording.256.zip)

**Comment by testershub** [comment]
I can reproduce this issue for build [1.2.0(23)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.2.0.(23) on Asus Nexus 7 Android 5.1.1.

**Comment by xiuie** [comment]
@testershub Please verify that appropriate warning messages are shown
