### ISSUE TITLE
[1.2.0 (23)] Xiaomi Note 3/ Android 5.1.1: "Error..Oops something went wrong. Please try again" message displayed for Motif and Find Music page.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#242]
Frequency: Every time

Steps to reproduce:
1: Launch the application.
2: Tap on Start
3: Tap on "Motif" tab from choose photo page.

Expected result: It should display available list of different categories photos.

Actual result: It shows "Error, Oops something went wrong. Please try again later." on trying to access motif tab.

Same issue also for Find Music.

**Comment by Dipamit** [comment]
I am getting this message also on Motorola Nexus 6, Android 6.0.1

**Comment by vysohanych** [comment]
Sometimes I can reproduce it on build 1.2.0.(23) on Samsung Galaxy Tab S 10.5 Android 4.4.2

**Comment by xiuie** [comment]
I think this means no internet connection. The same thing should happen 100% of the time when you go into airplane mode.

**Comment by hiteshbheda** [comment]
I can't reproduce this issue for build 1.3.0 (28) on Asus Zenfone Go / Android 5.1
