### ISSUE TITLE
[1.3.0 (24)] Asus Zenfone Go 4.5 / Android 5.1 - "AVI Unsupported format" Error - Select Video folder from Add Photos & Videos screen and check the available videos

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#254]
Frequency: Every time

Action:
1. Open Lomotif application
2. Click on START button on the home screen
3. Select Album tab from Add Photos & Videos screen
4. Tap on Videos folder from Add Photos & Videos screen
5. Check whether all videos display properly or not

Expected result: Only supported videos should be displayed

Actual result: Avi format videos (Not supported videos) also displays in the videos folder

![1](https://cloud.githubusercontent.com/assets/9691390/16721305/d2732c94-475b-11e6-8167-c1a7376a501e.png)

![2](https://cloud.githubusercontent.com/assets/9691390/16721304/d2684da6-475b-11e6-8474-40d7184e20ad.png)

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.3.0.(25) on Samsung Galaxy Tab S 10.5 Android 4.4.2.

But as I know it is not supported format for Android build

**Comment by hiteshbheda** [comment]
@xiuie Ok. Thanks for information!
