### ISSUE TITLE
[1.0.13] Motorola Nexus 6/ Marshmallow 6.0.1 - Create- Images are flicking while playing video.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#27]
Frequency : Sometime.

Action:
1. Tap on any created video.
2. Tap on Music for change.
3. Search for any Music and without select any music tap on Apply on top.
4. Check the video played again after it.

Expected Result: Video should be playing without any flicking.

Actual Result: Images are flicking during video playing.
[Flicking Images.zip](https://github.com/Lomotif/lomotif-android-issues/files/181208/Flicking.Images.zip)

**Comment by xiuie** [comment]
@Dipamit Will be helpful if you let me know approximately how often it happens.. e.g. only happened once although I created 50 Lomotifs while testing.

**Comment by Dipamit** [comment]
I got this issue 3 times during my testing out of approx 15 Lomotif created. I can say this should be analyzed at coding side once as I got three times and which seems major problem. I confirmed about network, so not related to network.

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this issue for build [1.0.14] for Asus Zenfone Go 4.5 / Android 5.1 and on Sony xPeria Z / Android 5.1.1
