### ISSUE TITLE
[1.0.13] Motorola Nexus 6/ Marshmallow 6.0.1 - Music- Cancel button is not working beside search Music.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#28]
Frequency : Always.

Action:
1. Tap on Start.
2. Select any Video and go next by tap on Apply.
3. Search for any Music and then try to tap on X icon beside search field.

Expected Result: Cancel should reset the entered value and should display back all results.

Actual Result: Cancel button is not working.
[Cancel Button on Video.zip](https://github.com/Lomotif/lomotif-android-issues/files/181443/Cancel.Button.on.Video.zip)

**Comment by xiuie** [comment]
@Dipamit Will be helpful if you let me know also pressing other things e.g. deleting your search keywords, or pulling to refresh, loads the songs.

**Comment by xiuie** [comment]
I will triage this bug assuming you CAN'T do that.

**Comment by Dipamit** [comment]
I did simple thing, enter keyword and tap on Cancel button. It should just remove the entered value. This things working proper on Choose video page. I already posted behavior of pulling to refresh behavior.

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can replicate the same issue every time on Sony xPeria Z / Android 5.1.1.
- When deleting search keyword will refresh the songs from server (correctly working)
- Enter keyword in search bar and pulling to refresh will give all songs list. (Not working properly - It should display only entered keyword results)
- Enter keyword and go back again load the song gives refreshed songs list (But search bar word should be cleared)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce it now for build [1.0.14] on Sony xPeria Z / Android 5.1.1 and on Asus Zenfone Go 4.5 / Android 5.1

Cancel button works correctly now.
