### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Back Button Bug on Music screen - While selecting music and try to go back on Find Music tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#3]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 photos from Camera folder from My Video tab
4. Select any song from Find Music tab
5. Click on Back button (available at top left corner) to go back at previous screen

Expected result: It should redirect us to previous screen / My video screen

Actual result: Back button does not work on Find Music tab

![screenshot_2016-03-15-22-22-40](https://cloud.githubusercontent.com/assets/9691390/13786251/cca5a2e4-eafc-11e5-9b23-ea1646583173.png)

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by vysohanych** [comment]
@xiuie @jpaulo1205 Can't reproduce on build 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this issue on build [1.0.14] with Sony xPeria Z / Android 5.1.1
