### ISSUE TITLE
[1.0.13] Motorola Nexus 6/ Marshmallow 6.0.1 - Music- Search Music with valid keyword is not working.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#30]
Frequency : Always.

Action:
1. Tap on Start.
2. Select any Video and go next by tap on Apply.
3. Search for any valid category e.g. Romantic in Music and then tap on search.

Expected Result: It should get matching result for Music. It should work like working in IOS application.

Actual Result: When you search for any Music with valid keyword. This is working proper with IOS application.
[Search Music not working.zip](https://github.com/Lomotif/lomotif-android-issues/files/181458/Search.Music.not.working.zip)

**Comment by jpaulo1205** [comment]
client side is only displaying what is returned by the server. I reckon it's due to the limited music source for Android client in server, can you confirm @ruiwen ?

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 @ruiwen I can replicate this issue on Sony xPeria Z / Android 5.1.1.

But as @jpaulo1205 is suggesting, it may be the server issue, may be they have limited source or no categories available for audio songs.

**Comment by ruiwen** [comment]
Sorry guys, yes, we're using a limited music source for testing on Android
now, so not all search terms may work.

Search for song terms that appear on the default song list that appears
instead (essentially just filtering the list, not searching).

/cc @hiteshbheda @jpaulo1205 @xiuie
