### ISSUE TITLE
[1.4.5(34)] Samsung Galaxy Tab S2 / 6.0.1,Samsung Galaxy Note 2 / 4.4.2 - Lomotif doesn't get deleted from device memory when user deletes the lomotif from "Home" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#330]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and create lomotif with any category.
3: Tap on "Export" option and skip the sharing.
4: Lomotif will saved in device memory.
5: Navigate to device gallery and check created lomotif is displayed.
6: Now, delete the lomotif from application's home screen.
7: Check if lomotif gets deleted from device memory too.

Expected result: The video from the phone memory should also get deleted as user explicitly deleting the video as there can be following issues:
1: Memory issue.
2: Repeated content- Suppose user wants to make the same video with one different image and he wants to share the saved video while accessing some other app (e.g.,WhatsApp) and when user will navigate to phone memory he might find two similar looking video (bad user experience).

Actual result: Lomotif doesn't get deleted from device memory when user deletes the lomotif from "Home" screen.

Refer following video for more details:
http://www.screencast.com/t/38u0nW8Jlzsd

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for Live build 1.4.4 (33) on Asus Zenfone Go / Android 5.1

**Comment by xiuie** [comment]
I think it's expected behavior. The Lomotif in your app is a project file.
