### ISSUE TITLE
[1.0.14] Asus Nexus 7 / Android 5.1.1 - Home screen - Not user friendly delete buttons on home screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#34]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Verify delete buttons on the home screen

Expected result: Delete buttons should more user friendly

Actual result: User sees not user friendly delete buttons

![2016-03-30_1009](https://cloud.githubusercontent.com/assets/3593359/14134519/86fce22e-f660-11e5-9bb0-e1aa593bffda.png)

**Comment by hiteshbheda** [comment]
@xiuie @pmtheint I can replicate this as Design Issue on Sony xPeria Z / Android 5.1.1

**Comment by pmtheint** [comment]
Noted and new button design is saved. Can close this issue now.
