### ISSUE TITLE
[1.4.5(34)] Samsung Galaxy Note 4 / 6.0.1 , Samsung Galaxy Note 2 / 4.4.2 - Preview is not displayed on "Create" screen when user creates lomotif with images from "Retrica" folder.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#343]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select images from "Retrica" folder.
3: Skip the music and proceed to "Create" screen.
4: Check if preview is not displayed on "Create" screen.

Expected result: Preview should be displayed when user creates lomotif with images from "Retrica" folder.

Actual result: Preview is not displayed on "Create" screen when user creates lomotif with images from "Retrica" folder, black screen is displayed.

Note: Issue is specifically observed when image doesn't have any effect.

Refer screenshot for more details.

**Comment by testershub** [comment]
![preview](https://cloud.githubusercontent.com/assets/18608449/17456181/5a68105c-5bec-11e6-8913-45624be2880a.jpg)

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.5 (34) on LG Nexus 5X Android 6.0.1 because "Retrica" folder is missing

**Comment by hiteshbheda** [comment]
@xiuie  I can't reproduce this issue for Live build 1.4.4 (33) on Asus Zenfone Go / Android 5.1 because "Retrica" folder is not available

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for Live build 1.4.4 (33) on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
I can reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go 4.5 / Android 5.1

**But it works perfectly for Retrica Videos. only Image preview is Black.**

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie This issue is reproducible for Retrica images only for build 1.4.7 (43) on Asus Zenfone Go / Android 5.1

But it is not reproducible for Retrica Videos

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.4.7-r2 (46)] on Samsung Galaxy Note 4 / 6.0.1.

Black frame is displayed on "Preview".

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by hiteshbheda** [comment]
@xiuie **I can reproduce this issue ONLY FOR RETRICA IMAGES** for build [1.5.0-r1 (49)] on Asus Zenfone Go 4.5 / Android 5.1

**But it works perfectly for Retrica Videos. only Image preview is Black.**

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.5-r4 (114)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by solgems** [comment]
Black frames image loading issue should be fixed. submit new ticket if necessary.

**Comment by Aboli-Testershub** [comment]
@solgems, Ok.
