### ISSUE TITLE
[1.4.6-r1 (37)] Asus Zenfone Go 4.5 / Android 5.1 - Facebook not working - In "Add photos and Videos" screen, under facebook folder no assets display

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#355]
Frequency: Every time

Pre-requisite: Login in Facebook account through Linked account section

Action:
1. Launch the app
2. Click on Start
3. Go to "Add photos and videos" screen
4. Click on Facebook folder
5. Check any images/videos display under facebook folder or not

Expected result: Images and Videos should be displayed according to Linked facebook account

Actual result: No image/videos under facebook account. It displays blank screen

**Comment by hiteshbheda** [comment]
@xiuie  I can still reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go / Android 5.1

**Blank screen displays even if user has linked facebook account in Linked Account section.**

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.4.7 (43)] on Asus Zenfone Go / Android 5.1

**Comment by xiuie** [comment]
Reproducible on Lomo.LG7

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r1 (49)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go/ Android 5.1

**Close for Build 1.5.0-r4**
