### ISSUE TITLE
[1.4.6-r1 (37)] Samsung Galaxy Note 2 / 4.4.2 - Export progress becomes zero and continuously exporting is displayed.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#357]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select any motifs from motif tab.
3: Skip the music and proceed to "Create" screen.
4: Shuffle the motifs or simply swipe left/right on the motifs thumbnails.
5: Tap on "Export" option.
6: Export progress starts.
7: Check if export process becomes zero and exporting never ends.

Expected result: User should be navigated to sharing screen.

Actual result: Export progress starts (randomly 50-80 % or less) and becomes zero and continuously exporting is displayed.

Refer following video for more details:
http://www.screencast.com/t/qWAfZrsyG

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Xiaomi Redmi Note 3/5.1.1 for build 1.4.6-r1.

Frequency: 3/5

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.4.6-r1 (37)] on Asus Zenfone Go 4.5 / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go / Android 5.1
