### ISSUE TITLE
[1.4.6-r2 (38)] Asus Zenfone Go 4.5 / Android 5.1 - Create header and image preview overlaps - At create screen preview of image and create header overlaps

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#382]
Frequency: Every time

Action:
1. Launch the app 
2. Tap on "START" button
3. Select few images from Camera Roll
4. Don't add any song and click on Apply at top right corner
5. On preview screen, check whether image and Create header overlaps or not

Expected result: Image should be resized and should not overlap with Create screen header

Actual result: Image is overlapped with create screen header

![screenshot_2016-08-24-11-07-14](https://cloud.githubusercontent.com/assets/9691390/17920824/484a99ce-69f4-11e6-8608-cbeaa88bb958.png)

![screenshot_2016-08-24-11-05-47](https://cloud.githubusercontent.com/assets/9691390/17920823/4848bb72-69f4-11e6-9f8e-e5be1e144f04.png)

**Comment by xiuie** [comment]
@hiteshbheda This is the same design as iOS.. For Square format, there's an overlap

**Comment by hiteshbheda** [comment]
@xiuie Ok. Thanks for update!
