### ISSUE TITLE
[1.4.6-r2 (38)] Asus Zenfone Go 4.5 / Android 5.1 - Exporting restarts and come to 0 % - Create lomotif with 3-4 motifs -> drag time slider at the end and export it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#394]
Frequency: Every time

Action:
1. Launch the app
2. Click on "START" button
3. Select 3-4 motifs from "friendship" category
4. Don't add any song and create lomotif
5. On create screen, Tap on added first motif
6. From the timeline, drag time slider at the end (Right side)
7. Do the same process for all the added motifs
8. Now click on Export button
9. Export process will start and check whether it completes or not

Expected result: Export process should start and should successfully complete

Actual result: Export process started, goes upto 50 - 60 % and again restarts from 0 % and not increased now

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.4.6-r2 (38)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung  Galaxy S4 / 5.0.1.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7 (43) on LG Nexus 5X Android 6.0.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go / Android 5.1

**Close for Build 1.5.0-r4**
