### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Play button Bug - Play / Pause button not available to play and pause created lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#4]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 photos from Camera folder from My Video tab
4. Select any song from Find Music tab
5. Now, created lomotif will play automatically
6. Try to pause lomotif

Expected result: Lomotif should be pause and play when clicked on screen

Actual result: Play / Pause button not available, while clicking on lomotif screen not creating any effect

![screenshot_2016-03-15-22-54-08](https://cloud.githubusercontent.com/assets/9691390/13787218/1241d184-eb01-11e5-8b00-fee192e25bad.png)

**Comment by vysohanych** [comment]
@xiuie @jpaulo1205 Can't reproduce on build 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this issue on build [1.0.14] with Sony xPeria Z / Android 5.1.1
