### ISSUE TITLE
[1.4.7 (43)] Asus Zenfone Go 4.5 / Android 5.1 - Application Crash - Open existing lomotif created in earlier version with Retrica image and video

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#401]
Frequency: Many times (Frequency: 5 / 10)

Action:
1. Launch the app
2. Open any existing lomotif created in earlier build with Retrica image / video
3. Check whether lomotif load or not

Expected result: Selected lomotif should be loaded

Actual result: Application crash

**Comment by Dipamit** [comment]
@xiuie : Application not crash but getting Black frame on Preview page.
Device:  Xiaomi RedMi note 3/5.1.1

![screenshot_2016-09-02-18-57-17_com lomotif android dev 1](https://cloud.githubusercontent.com/assets/17335200/18205589/673c9dc0-7140-11e6-94bb-38db0e0a5d14.png)

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7 (43) on LG Nexus 5X Android 6.0.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go / Android 5.1

**Close for Build 1.5.0-r4**
