### ISSUE TITLE
[1.4.7(43)] Xiaomi RedMi Note 3/5.1.1 Error message for Motif and Find Music.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#411]
Frequency: Always
1. Open application and tap on Start.
2. Tap on Motif and Verify page.
3. Tap on Album and select any Image.
4. Tap on Next and Verify Find Music page.

Expected result: Motif should display videos.
                           Find Music should display Songs.

Actual result: Error message displayed for Motif and Find Music.

![screenshot_2016-09-02-18-10-45_com lomotif android dev 1](https://cloud.githubusercontent.com/assets/17335200/18205714/22dc519c-7141-11e6-9de4-dc79c5397cdf.png)

![screenshot_2016-09-02-18-10-19_com lomotif android dev 1](https://cloud.githubusercontent.com/assets/17335200/18205734/3a518202-7141-11e6-9c74-51d0b8565bf7.png)

**Comment by Dipamit** [comment]
@xiuie : Reproducible on Motorola Nexus 6/6.0.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.4.7 (43)] on Samsung Galaxy Note 4/ 6.0.1, Samsung Galaxy S4 / 5.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.4.7 (43)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I have received this error message for Find Music

![screenshot_2016-09-02-16-22-52](https://cloud.githubusercontent.com/assets/9691390/18209818/21615a12-7153-11e6-8fab-5cc3099b7f32.png)

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7 (43) on LG Nexus 5X Android 6.0.1
