### ISSUE TITLE
[1.4.7-r1 (45)] Samsung Galaxy Note 2 / 4.4.2 - Application is crashing when user create lomotif with music from "My Music" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#439]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select a video from "Instagram / Snapchat".
3: Select any song from "My Music" tab.
4: Proceed to "Create" screen.
5: Check if application is crashing.

Expected result: Lomotif should get created with selected music.

Actual result: Application is crashing when user create lomotif with music from "My Music" tab.

Refer following video for more details:
http://www.screencast.com/t/kQ4ivvW3be

**Comment by testershub** [comment]
Please see issue is specifically observed for Samsung Galaxy Note 2 / 4.4.2.
I can't reproduce this issue on Nexus 5 / 6.0.1, Samsung Galaxy S4 / 5.0.1 and Samsung Galaxy Note 4 / 6.0.1.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7-r1 (45) on LG Nexus 5X Android 6.0.1

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.4.7-r1 (45)] on Asus Zenfone 5 / 4.4.2.

**Comment by kimberlyctse** [comment]
Can’t reproduce for build 1.4.7 (47) on Samsung Galaxy Core Prime/ SM-G360T1/ 5.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)] on Samsung Galaxy Note 2 / 4.4.2.

Close for Build 1.5.0-r4
