### ISSUE TITLE
[1.9.4(1.9.17) IPad3 / IOS 9.3.5 - Application is showing error while sliding music tray on Video screen.

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-android-issues#457]
Frequency:  Sometimes

Action:
1. Launch the app.
2. Tap on any video on Home screen.
3. Scroll down upto the audio section , while video is playing.
4. Slide left OR  Right music tray.
5. Verify error does get displayed.

Expected result: System should not error.

Actual result: Application is providing an error message " Error - 11800 An unknown error occured(-12780)

Refer following image for more details:
http://prnt.sc/chy491

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.19] on iPhone 6S / 10.0.1.
It is working as expected.

But when I drag the waveform and immediately taps on waveform again it shows error "11800".

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.4.7-r2 (46) on LG Nexus 5X Android 6.0.1

**Comment by pallavipillai** [comment]
Moving this issue in iOS section
