### ISSUE TITLE
[1.4.7-r2(46)] Asus Nexus 7 / Android 5.1.1 - [Russian localization] - All application is not localized to Russian

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#465]
Frequency: Every time

Steps: 
1. Switch to Russian language on device
2. Launch the application
3. Observer all application

Actual result: All application is not localized to Russian

Expected result: All application should be localized to Russian

Video: 
[mobizen_20160924_120434.zip](https://github.com/Lomotif/lomotif-android-issues/files/491043/mobizen_20160924_120434.zip)

![screenshot](https://cloud.githubusercontent.com/assets/3593359/18807488/28c6073a-8251-11e6-8f4b-1c2fb31e2b54.jpg)

**Comment by xiuie** [comment]
Got it. Nexr build will be localized to Russian, Norwegian and Swedish. please look out for it but dont need to log localization bugs separately. if u notice anything, maybe just list it.
