### ISSUE TITLE
[1.5.0-r1 (49)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - Motif's preview is overlapping on selected border.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#467]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START >>Motifs" tab.
3: Tap on "Friendship" category and select any motif.
4: Play the selected motif.
5: Check if preview is overlapping on selected border.

Expected result: Preview should not be overlap on selected border.

Actual result: Preview is overlapping on selected border.

Please refer screenshot for more details.

**Comment by testershub** [comment]
![preview_overlap](https://cloud.githubusercontent.com/assets/18608449/19234706/fa007c84-8f0a-11e6-98a8-1b2874da2a1c.jpg)

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.5.0-r1 (49) on LG Nexus 5X Android 6.0.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)].

Close for Build 1.5.0-r4
