### ISSUE TITLE
[1.5.0-r1 (49)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - Irrelevant confirmation message "Do you want to go back to home page?" is displayed after tapping on "Home" icon.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#468]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "START" and select few motifs.
3: Add/ skip music and proceed to "Create" screen.
4: Tap on "Home" icon.
5: Check if irrelevant confirmation message "Do you want to go back to home page?" is displayed.

Expected result: Relevant confirmation message "Do you want to go back to home screen?" should be displayed.

Actual result: Irrelevant confirmation message "Do you want to go back to home page?" is displayed after tapping on "Home" icon on "Create" screen.

Refer screenshot for more details.

**Comment by testershub** [comment]
![confirmation_msg](https://cloud.githubusercontent.com/assets/18608449/19235520/c6ac67c6-8f0f-11e6-9ac6-c65732c18f73.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this general issue for build [1.5.0-r1 (49)] on Asus Zenfone Go / Android 5.1

**But I don't think it's a Bug.**
