### ISSUE TITLE
[1.5.0-r1 (49)] LG Nexus 5X / Android 6.0.1 - Smile from title is cropped on Create screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#475]
Frequency: Every time

Action:
1. Open Lomotif application
2. Click on START button
3. Select 1 photo on Add Photos & Videos screen
4. Tap next button on Add Photos & Videos screen
5. Don't select song on Find Music screen
6. Tap next button on Find Music screen
7. Add any text with smile in Enter title tab

Actual result: Smile from title is cropped on Create screen

Expected result: Smile from title should not be cropped on Create screen

![2016-10-10_1656](https://cloud.githubusercontent.com/assets/3593359/19238520/90351756-8f0a-11e6-8624-bb78c3858c9a.png)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy S4 / 5.0.1.
Please see, issue is specifically observed when user set "GIPSIERO" font for title.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.5.0-r1(49)

Agree with @testershub , Issue is specifically observed for GIPSIERO OWTLINE font.

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1

**Comment by vysohanych** [comment]
Close now

@xiuie I can't reproduce it on build 1.5.0-r5 (53) on LG Nexus 5X Android 6.0.1
