### ISSUE TITLE
[1.5.0-r1 (49)] Asus Zenfone Go / Android 5.1 - Keyboard does not disappear - Send Feedback

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#476]
Frequency: Every time

Action:
1. Launch the app
2. Tap on Hamburger icon to open Setting menu
3. Click on "Send Feedback" option
4. Select Appropriate mail box (Gmail) to send feedback
5. Send mail
6. Check whether keyboard disapper after seding feedback or not

Expected result: Once feedback has sent, then keyboard should disappear from Setting screen

Actual result: Even though feedback has sent, the keyboard still displays on Setting screen

![screenshot_2016-10-11-14-59-46](https://cloud.githubusercontent.com/assets/9691390/19265647/930b5670-8fc3-11e6-89eb-944ce894be80.png)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.5.0-r1(49)

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go/ Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r5 (53)] on Asus Zenfone Go/ Android 5.1

Close for Build 1.5.0-r5
