### ISSUE TITLE
[1.5.0-r1 (49)] Asus Zenfone Go / Android 5.1 - Thumbnails disappear - Create lomotif using Motifs and Clear cache

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#480]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "Start" button
3. Select few motifs from any Motif category
4. Don't select any song and create lomotif 
5. Save lomotif
6. From Setting menu -> Clear cache
7. Close Application
8. Launch App again
9. Check on the home screen whether recently created lomotif's Thumbnail (Album art) available or not

Expected result: Thumbnails (Album arts) should display even though user has clear the cache

Actual result: Clearing cache also erase the thumbnails (album arts) from the app home screen

IMPORTANT: This issue is also applicable and reproducible for Motifs / Facebook images / Instagram images

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1.

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.5.0-r1(49)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go/ Android 5.1

**Close for Build 1.5.0-r4**
