### ISSUE TITLE
[1.5.0-r1(49) Xiaomi RedMi Note 3/5.1.1 Application crash on tapping Feed Screen.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#485]
Frequency: Most of the time  8/10
1. Open application and tap Feed Icon.
2. Tap on Feed page multiple time.

Expected result: Application should not crash.

Actual result: 
1. Green Blank page displayed instead of Feed videos.
2. Application crash on tapping Feed page multiple time.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.
Please see, application is crashing when user tap multiple times on "feed" screen (Blank green screen) in "Airplane" mode.

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r4 (52)] on Samsung Galaxy Note 2 / 4.4.2. 
Application is crashing after tapping on any video from feed multiple times in online mode.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.5.0-r5 (53)] on Samsung Galaxy Note 2 / 4.4.2.
Application is crashing after tapping on any video from feed multiple times in online mode.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r6 (54)] on Samsung Galaxy Note 2 / 4.4.2.
