### ISSUE TITLE
[1.5.0-r1 (49)] Samsung Galaxy Note 4 / 6.0.1 - Application is crashing when user shake the device to shuffle assets.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#486]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select 3 videos form "Lomotif" folder.
3: Add music and proceed to "Create" screen.
4: Shake the device to shuffle the assets.
5: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user shake the device to shake the assets.

Refer following video for more details:
 http://www.screencast.com/t/cyxJOIaWox

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.5.0-r3(51)

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r6 (54)] on Samsung Galaxy Note 4 / 6.0.1.
