### ISSUE TITLE
[1.5.0-r3 (51)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Music names are not aligned properly on "Find Music" tab (Align to left).

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#488]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select 1 photo.
3: Proceed to "Find Music" screen.
4: Check if song names are not aligned properly.

Expected result: Music name should be align to left.

Actual result: Music names are not aligned properly on "Find Music" tab (Align to left).

Refer screenshot for more details:

**Comment by testershub** [comment]
![name_alignment](https://cloud.githubusercontent.com/assets/18608449/19432997/8d3bd7fc-947c-11e6-8a24-19fa258da78a.jpg)

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.5.0-r3 (51) on LG Nexus 5X Android 6.0.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)].

Close for Build 1.5.0-r4
