### ISSUE TITLE
[1.5.0-r3 (51)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - User is not able to search "Motifs" on "Motifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#491]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "START >> Motifs" tab.
3: Enter category name to search and tap on "Enter" key on keypad.
4: Check if entered keyword is getting deleted.

Expected result: User should be able to search any motif category from "Motifs" tab.

Actual result: Entered keyword is getting deleted when user try to search the motifs category.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**But I only get "Return" button, I don't get "Enter" or "Search" button on Keyboard.**

![screenshot_2016-10-17-16-18-06](https://cloud.githubusercontent.com/assets/9691390/19434866/756fd458-9485-11e6-8293-9c0e38bd93ff.png)

**Comment by testershub** [comment]
@xiuie Similar issue is observed for "Find Music" tab.

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.5.0-r3(51)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r4 (52)].

Close for Build 1.5.0-r4
