### ISSUE TITLE
[1.5.0-r3 (51)] LG Nexus 5X / Android 6.0.1 - Video plays inside the thumbnail on 'Add Photos & Videos' screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#492]
Frequency: Every time

Action:
1. Create a new video with the device camera in portrait mode
2. Open Lomotif application
3. Click on START button
4. Open folder with created video
5. Tap play button on the thumbnail of video

Actual result: Video plays inside the thumbnail

Expected result: Video plays instead all thumbnail

Video: [Recording #361.zip](https://github.com/Lomotif/lomotif-android-issues/files/533424/Recording.361.zip)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by vysohanych** [comment]
Close now

@xiuie I can't reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1
