### ISSUE TITLE
[1.5.0-r3 (51)] LG Nexus 5X / Android 6.0.1 -Application crashes when user pull down to refresh on new video feed screen in Airplane mode

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#495]
Frequency: Every time

Action:
1. Turn on Airplane mode
2. Open Lomotif application
3. Swipe the home screen to right side
4. Pull down to refresh on new video feed screen => Infine loader appears on the new video feed screen
5. Pull again down to refresh on new video feed scree

Actual result: Application crashes

Expected result: Application should not crash and infine loader should not appear

Video: [Recording #555.zip](https://github.com/Lomotif/lomotif-android-issues/files/533947/Recording.555.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r3 (51)] on Asus Zenfone Go / Android 5.1

**Comment by vysohanych** [comment]
Close now

@xiuie I can't reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1
