### ISSUE TITLE
[1.5.0-r3 (51)] Samsung Galaxy Tab S2 / 6.0.1, Samsung Galaxy Note 4 / 6.0.1 - Blank white screen is displayed under "Instagram" option.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#504]
Frequency: Every time

Action:
Precondition:- User should have logged in to "Instagram"
1: Launch the app.
2: Tap on "START".
3: Tap on "Instagram" option ( Assets will be displayed).
4: Select one video/picture and tap on next option.
5: Tap on "Back" option (User will navigate back to "Instagram" option).
6: Check if the blank white screen is displayed instead of "Instagram" assets.

Expected result: "Instagram" assets should be display under "Instagram".

Actual result: 
1: Blank white screen is displayed under "Instagram".
2: Assets are displayed when user refresh the "Instagram" screen.

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.5.0-r4 (52)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.5.0-r6 (54)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.
