### ISSUE TITLE
[1.5.0-r6 (54)] Asus Zenfone Go / Android 5.1 - Song added without selection - Tap on My Music song and move to Find Music tab and then create lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#530]
Frequency: Every time

Action:
1. Launch the app
2. Tap on START
3. Select any asset
4. Go to My Music tab
5. Tap on any song from list
6. Move to Find Music tab
7. Don't select any song and create lomotif
8. Check on Preview screen, whether song added or not

Expected result: Song should not be added because  in step 6 and 7, user has not selected any song

Actual result: Even though user has not selected any song then also song is added in created lomotif

**Comment by testershub** [comment]
@hiteshbheda In above mentioned step - 4, you are saying tap on any song from the list. So the song is selected and once you navigate to "Create" screen from "Find Music" screen, selected music from "My Music" tab is getting added.
