### ISSUE TITLE
[1.5.0-r6 (54)] Samsung Galaxy S4 / 5.0.1, Nexus 5 / 6.0.1 - User is not able to shuffle added assets by shaking the device.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#531]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select few assets.
3: Add / skip the music and proceed to "Create" screen.
4: Shake the device to shuffle the assets.
5: Check if user is able to shuffle assets by shaking the device.

Expected result: Assets should shuffle by shaking the device.

Actual result: User is not able to shuffle added assets by shaking the device.

**Comment by hiteshbheda** [comment]
@xiuie I think it's not a bug. Shuffle functionality may not been implemented yet.

**Comment by xiuie** [comment]
@testershub @hiteshbheda Have verified that Shake to Shuffle SHOULD exist in Android. We've recently increased the tolerance so can you try to shake harder? It should work.
