### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1 - Application is crashing when user try to "Sign In" in offline mode. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#536]
Frequency: Every time

Action:
1: Launch the app.
2: Turn of the internet connection.
3: Enter email and password.
4: Tap on "Sign In" button.
5: Check if application is crashing.

Expected result: Warning message "No Internet Connection" should be displayed when user try to "Sign In" in offline mode.

Actual result: Application is crashing when user try to "Sign In" in offline mode. 

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwR0w1bkFITmxGbDA

**Comment by testershub** [comment]
@xiuie Following error message is displayed when user try to "Sign Up" in offline mode.

![sign_up_error](https://cloud.githubusercontent.com/assets/18608449/20179504/7495e022-a77c-11e6-9247-fb4e2ae4b628.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie One more observation, similar error message (Highlighted in the above screenshot) is displayed when user taps on "Forgot Password >> Recover" option in offline mode.

**Comment by ayaadel87** [comment]
I can reproduce this issue for build [1.6.0-r6 (64)] on  sony z2(6.0.1)

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
