### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - "Sign up instead?" hyperlink is not functional on "Recover Password" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#538]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Sign In" option.
3: Tap on "Forgot Password?" option.
4: Enter invalid email address and tap on "Recover" button.
5: Tap on "Sign Up instead?" hyperlink.
6: Check if user is navigated to "Sign Up" screen.

Expected result: User should be navigated to "Sign Up" screen after tapping on "Sign up instead?" hyperlink on "Recover password?".

Actual result: "Sign up instead?" hyperlink is not functional on "Recover password" screen.

Refer screenshot for more details.

**Comment by testershub** [comment]
![recover_pass](https://cloud.githubusercontent.com/assets/18608449/20180114/1452eb76-a77f-11e6-917d-c4d35a58414d.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)]
