### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - User is not able to change the password from "Setting" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#539]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Sign In" option.
3: Sign in with valid credentials.
4: Tap on "Setting >>Password".
5: Enter "Current Password", "New Password" and "Repeat Password".
6: Check if "Ok" tick is getting enabled.

Expected result: User should be able to change the password from "Setting" screen.

Actual result: "Ok" tick is not getting enabled when user try to change the password from "Setting" screen.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
