### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Application is crashing when user try to change "Email" address from "Setting" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#540]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on "Setting >> Email" option.
4: Edit/ change the email address.
5: Tap on tick option at right top corner.
6: Check if application is crashing.

Expected result: User should be able to change the "Email" address from "Setting" screen.

Actual result: Application is crashing when user try to change the "Email" address.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by ayaadel87** [comment]
i  can reproduce this issue for build [1.6.0-r4 (64)] on sony z2(6.0.1)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue first time for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

But if I change Email address 3-4 times, then application crash. (As mentioned in #567 )
