### ISSUE TITLE
[1.6.0 -r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Close option "X" is not functional.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#543]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "Skip for Now" option.
3: Tap on user icon at bottom.
4: Tap on "X" option at top right corner.
5: Check if "X" option is functional.

Expected result: "X" option should be functional.

Actual result: "X" option is not functional.

Refer screenshot for more details.

**Comment by testershub** [comment]
![close_option](https://cloud.githubusercontent.com/assets/18608449/20181372/f6219dd2-a783-11e6-81ce-f16920948f33.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by ayaadel87** [comment]
same issue occurs  for build [1.6.0-r6 (66)/Sony Z2/6.0.1

**Comment by testershub** [comment]
@xiuie Close option "X" is not available on "Sign Up / Sign In" screen.
