### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - "Email" and "Password" fields doesn't get cleared when user sign out from the account. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#544]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Skip for Now" option.
3: Tap on user icon at bottom.
4: Login with valid credentials.
5: Tap on "Setting >> Sing Out".
6: Navigate to "Sign In" screen.
7: Check if "Email" and "Password" fields are getting cleared.

Expected result: "Email" and "Password" fields should get cleared when user sign out form the account.

Actual result: "Email" and "Password" fields doesn't get cleared when user sign out form the account.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
