### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Back option "<" is not functional on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#546]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in or proceed without sign in.
3: Tap on "START" and select few motifs.
4: Add any music and proceed to "Create" screen.
5: Export the lomotif.( User will navigate to "Saving your Lomoitf" screen)
6: Tap on back option "<" at top left corner.
7: Check if user is navigated to "Create" screen.

Expected result: User should be navigated back to "Create" screen when user taps on back option "<" on "Saving you Lomotif" screen.

Actual result: Back option "<" is not functional on "Saving your Lomotif" screen.

Refer screenshot for more details.

**Comment by testershub** [comment]
![back_option](https://cloud.githubusercontent.com/assets/18608449/20206193/c0ea2266-a804-11e6-8a69-39e95b27016b.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
