### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - "In Progress" and "Lomotifs" tabs are not functional.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#551]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on user icon at bottom.
4: Tap on "Lomotifs / In Progress" tab.
5: Check if "Lomotifs" and "In Progress" tabs are functional.

Expected result: "Lomotifs" and "In Progress" tabs should be functional.

Actual result: "Lomotifs" and "In Progress" tabs are not functional.

Refer screenshot for more details.

**Comment by testershub** [comment]
![tabs](https://cloud.githubusercontent.com/assets/18608449/20207497/a28a599a-a80d-11e6-9e92-93d7b2188c55.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
