### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user taps on any option on "Setting" screen in offline mode.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#553]
Frequency: Every time

Action: 
1: Launch the app.
2: Sign in with valid credentials.
3: Turn off the internet connection.
4: Tap on "Setting" option.
5: Tap on any option. e.g. "Username/ Display Name".
6: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user taps on any option on "Setting" screen in offline mode.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwZE9YZ2NRS09XaDg

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
