### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - User is not able to sign-out.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#556]
Frequency: Every time

Action:
Pre-condition:- User should have logged-in with the same account on two different devices(say A and B).
1: From device A, launch the app.
2: Tap on "Setting>>Sign out" option.
3: User will be successfully sign-out from the account.
4: From devices B, tap on "Setting >> Sign out".
5: Check if the user is not able to sign out.

Expected result: User should be able to sign-out from the account.

Actual result: User is not able to sign-out.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwdzEwT1dVUXZ2OEU

**Comment by testershub** [comment]
@xiuie: Application is crashing when user tries to change setting on device B.
-Continuous loading sign is displayed at "User profile" screen.

**Comment by testshadab** [comment]
Yes, I am able to reproduce this issue. I can not signed out from the 2nd device.

**Comment by xiuie** [comment]
@testshadab In future can you state which device model you've used to reproduce this for our reference? For example "I can reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy On 5" in the comments. Thanks!

**Comment by testshadab** [comment]
@xiuie :- I have 2 Android Devices one is Samsung Galaxy J Max/Android 5.1.1 and Micromax Sliver 5/ Android 5.1 and I did Sign-out from the Samsung Galaxy J Max/Android 5.1.1 successfully but after that when I try to Sign-out from the  Micromax Sliver 5/ Android 5.1 then I can not Sign-out.

Are you tying to replicate this issue with same account on different devices?
