### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Exported lomotif doesn't get saved in the device gallery (Device Storage).

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#558]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Skip for Now" option.
3: Tap on "START" and create a lomotif.
4: Export the lomotif. (User will be navigated to "Save your Lomotif" screen)
5: Observe "Save to Gallery" checkbox is checked.
6: Tap on "Make Lomotif" button.
7: Navigate to device gallery.
8: Check if exported lomotif is displayed in "Lomotif Staging" folder.

Expected result: Exported lomotif should be displayed / saved in device gallery.

Actual result: Exported lomotif doesn't get saved in the device gallery.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwYkVVd00xbU1sd2M

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by ayaadel87** [comment]
i can reproduce this bug on sony z2/6.0.1  for build [1.6.0-r6 (66)

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r16 (76)].  
Please see, issue is reproducible when is logged in.
Exported lomotif is not getting saved in device storage (Device Gallery).

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1
