### ISSUE TITLE
[1.6.0-r4 (64)] Asus Zenfone Go / Android 5.1 - Application Crash - Tap on Skip for now -> Enter Email, Password and User id

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#559]
Frequency: Every time

Action:
1. Launch the app.
2. Tap on "Skip for Now" option.
3. Tap on user icon at bottom.
4. Enter valid Email, any Password and userid
5. Click on "Let's Go"
6. Check whether application crash

Expected result: User should able to create new account or login with existing email

Actual result: Application crash

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.
It is working as expected.

**Comment by xiuie** [comment]
@hiteshbheda I don't see a "Let's Go" button in Step 5. Can you send over a video?

**Comment by testershub** [comment]
@xiuie He is talking about "Sign Up" process. "Let's Go" button is displayed while "Sign Up" process. You have to "Sign Up" in 4th step.

**Comment by hiteshbheda** [comment]
@xiuie @testershub Yes, In step #5, Enter valid email, password and click on Next / Done, it will display "Let'go button" at Sign up page.

Still I'm getting application crash everytime. 

Please find attached video link.

[Video](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UV2gxeWJDM295dFk)

**Comment by ayaadel87** [comment]
I can't reproduce this issue for build [1.6.0-r4 (64)] on sony z2(6.0.1)
i can sign up successfully

**Comment by xiuie** [comment]
@hiteshbheda I think the critical information here is that the email has to be already registered?

**Comment by hiteshbheda** [comment]
@xiuie Yes, the email has to be already registered

**Comment by xiuie** [comment]
Ok then we'll refer to the other bug for now. Thanks.

**Comment by testshadab** [comment]
@xiuie - I can reproduce this issue for build [1.6.0-r4] on Samsung Galaxy J Max Tab /Android 5.1.1.

Here are the steps to reproduce:-

Frequency: Every Time

Steps to reproduce :-
1. Launch Lomotif app on Samsung Galaxy J Max/Android 5.1.1.
2. Tap on "START" button.
3. Select the Image from Gallery.
4. Tap on "Next" at the top right side.
5. Again tap on "Next" at the top right side, it will give you message to add video.
6. Tap on "OK".
7. Tap on "Export" at the top right side.
8. Tap on "Make Lomotif" button.
9. Press Mobile back button.
10. Tap on user icon at bottom, you will get Sign Up screen.
11. Enter Already Registered email (test.shadab@gmail.com).
12. Enter Password and tap on "Sign up" button.
13. Enter Username as "test.shadabff".
14. Tap on "Let'go button".

Expected Result: Application should give error like "This email is already exists".

Actual result: Application crash

**Comment by hiteshbheda** [comment]
@xiuie @testshadab I can reproduce this issue (Application crash) for build [1.6.0-r6 (66)] on Asus Zenfone Go / Android 5.1
