### ISSUE TITLE
[1.6.0-r4 (64)] - User is able to "Reset" password as "Single character".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#566]
Frequency: Every time

Action: 
Precondition: User should have sign up for "Lomotif".
1: Launch the app.
2: Tap on "Sign In" option.
3: Tap on "Forgot password" option.
4: Enter valid registered email address and tap on "Recover" button.
5: Navigate to registered email account and click on "Reset password" button.
6: Enter single characters in "Password" and "Conform Password" fields and click on "Reset Password".
7: Check if warning message is displayed for single character password.

Expected result: Warning message should be displayed when user try to reset password as Single character.

Actual result:
1: User is able to reset password as "Single Character".
2: "Sing In" button is not getting enabled when user try to sign in with single character password after reset password as single character.

Refer screenshot for more details.

**Comment by testershub** [comment]
![reset_pass](https://cloud.githubusercontent.com/assets/18608449/20257431/86f4b630-aa6f-11e6-800c-6d3c27c70551.jpg)

**Comment by xiuie** [comment]
I can reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy On 5 (Lomo.on5)

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
But, No warning message is displayed when user try to set password as single character or less than 8 characters.
