### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Continuous loading is displayed at "User" screen in offline mode.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#568]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Turn off the internet connection.
4: Tap on user icon at bottom (Below the "START" button)
5: Check if username and other information is displayed.

Expected result: Warning message should be displayed when user navigates to "User" screen in offline mode.

Actual result: Continuous loading is displayed when user navigates to "User" screen in offline mode.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwWV80TlZvbEVybU0

**Comment by hiteshbheda** [comment]
@xiuie  I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
