### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user minimize the app while exporting the lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#569]
Frequency: Every time

Action:
1: Launch the app.
2: Sign In with valid credentials.
3: Tap on "START" and select few assets from "Lomotif staging" folder.
4: Add any music and proceed to "Create" screen.
5: Tap on export option (Export progress will be displayed)
6: Minimize the app and wait for few seconds.
7: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user minimize the app while exporting the lomotif.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwc1ZGXzNpNzZBX0U

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Nexus 6/7.0 
             Not able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1

**Comment by testershub** [comment]
@xiuie Verified (with and without login). Issue is resolved for version [1.6.0-r16 (76)].
