### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - "Email" field doesn't get cleared when user sends "Recover Password" link.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#571]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Sign In".
3: Tap on "Forgot Password" option.
4: Enter valid registered email address and tap on "Recover" button.
5: Tap on "OK" button on "Check your email" pop up.
6: User will navigate to "Recover Password" screen.
7: Check if email field gets cleared.

Expected result: "Email" field should get cleared when user sends "Recover Password" link.

Actual result: "Email" field doesn't get cleared when user sends "Recover Password" link.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go/ Android 5.1
