### ISSUE TITLE
[1.6.0-r4 (64)] Sony Z2 / 6.0.1/App Crashed when user enter an already registered email

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#575]
Frequency:Every time

Steps:
1-Launch the app
2-click on sign up
3-Enter an already registered email address and enter any password,
4-Click on sign up
5-Enter any user name and click on"lets go"

Expected Result
at step "3" above, an alert message should appear stating that this email is already registered

Actual Result:
User can proceed with signing up with registered email address but the app crashes after step 5

**Comment by hiteshbheda** [comment]
@xiuie Duplicate #559

**Comment by Dipamit** [comment]
@xiuie: Application not crashed but no validation message for using same Email, Password and username for registration.

User can register multiple time with same Email address,Password and Username.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r6 (66)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

Shows error message "Oops, something went wrong, Please try again."
