### ISSUE TITLE
[1.6.0-r4 (64)] Sony Z2 / 6.0.1/User can enter" invalid" email address in "Forgot password" link

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#578]
Frequency:Every time
Steps:
- Launch the app
- Click on sign in
- Click on forgot password
- Enter invalid email address

Expected Result:
An alert should appear that this email is not a valid email address/Registered email address

Actual Result:
invalid email address is accepted and pop up appears stating that email address has been sent to recover password

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
