### ISSUE TITLE
[1.6.0-r4(64) Xiaomi RedMi Note 3/5.1.1 Validation message is not removed after entering proper email address.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#581]
1. Open application.
2. On Login/Sign up page tap on Login.
3. Tap on Forget Password.
4. Enter invalid email address and tap on "Recover!"
5. Verify that validation message displayed "No such email exist".
6. Again enter Valid email address and tap on "Recover!"
7. "Check your email" page displayed.
8. Tap on "Ok" and Verify displayed page.

Expected result: Validation message should disappear while entering valid email.

Actual result: Validation message remain unchanged after entering valid Email

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
