### ISSUE TITLE
[1.6.0-r4(64)] Nexus 6/7.0 No back button or exit button on share screen.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#590]
1. Open application.
2. Tap on start and select any images.
3. skip songs and tap on Next.
4. Tap on export.
5. On Saving lomotif Screen select "Save to Gallary" and tap on "Make Lomotif"

Expected result: It should display back button or Exit button for not sharing Lomotif or get back.

Actual result: There are no option to get back or exit share screen.
![screenshot_20161115-154220 1](https://cloud.githubusercontent.com/assets/17335200/20302072/de4e20ce-ab4b-11e6-951d-fb085abbf07c.png)

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r16 (76)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.
Back option "<" is not displayed on "Share" screen when user navigates to "Share" screen with or without login.
