### ISSUE TITLE
[1.6.0-r4 (64)] Google Pixel / 7.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user taps multiple times on tick mark while updating "About Me" section.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#592]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on "Setting >> About Me" section.
4: Update "About Me" field and tap multiple times on tick mark at top right corner.
5: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user taps multiple times on tick mark while updating "About Me" section.

Please refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwOTRyQmZNMFJoRXM

Note: Please see application is crashing for all fields on "Setting" screen.

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by Dipamit** [comment]
@xiuie: Device : Xiaomi RedMi Note 3/5.1.1
1. While tapping on any field of Profile, page navigate to "Start" page. 
2. Username field displayed "Username" and Email field displayed "Add email"  even user is already logged in.
3. On tapping Login icon from start page below "start", it displayed endless loading.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r6 (66)] on Asus Zenfone Go / Android 5.1

**Comment by testshadab** [comment]
@xiuie - I can reproduce this issue for build [1.6.0-r6 (66)] on Samsung Galaxy J Max Tablet/Android 5.1.1.

**Comment by xiuie** [comment]
@Dipamit Is this a separate bug? Can you provide some screenshots as I don't fully understand

**Comment by Dipamit** [comment]
@xiuie: After reinstall build 1.6.0-r4(64), I can not reproduce above mention issue on Xiaomi RedMi Note 3/5.1.1

**Comment by Dipamit** [comment]
@xiuie: Please refer attached video, Yesterday issue occur on Xiaomi RedMi note 3/5.1.1  but today i am facing on Nexus 6/7.0

[2016_11_16_16_03_57.zip](https://github.com/Lomotif/lomotif-android-issues/files/594335/2016_11_16_16_03_57.zip)

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
