### ISSUE TITLE
[1.6.0-r6 (66)] Asus Zenfone Go / Android 5.1 - Keyboard does not disappear - Enter text on Export ("Saving your Lomotif") screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#596]
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential through Email id and password
3. Create lomtif with one photo and with / without song
4. Click on Export button
5. On "Saving your Lomotif" screen, enter some text in text area in  "Say something about this lomotif" box
6. Try to submit your text
7. Check whether keyboard disappear and user is able to save text or not

Expected result: 
1. Keyboard should disappear 
2. User should be able to save entered text

Actual result: 
1. Keyboard does not disappear
2. User is not able to save entered text

**Comment by ayaadel87** [comment]
i can reproduce this bug on sony z2/6.0.1 for build 1.6.0-r6 (66)

**Comment by Dipamit** [comment]
@xiuie: I can reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r16 (76)

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

Works properly

Close for build [1.6.0-r22 (82)]
