### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy S6 / 6.0.1,Samsung Galaxy S4 / 5.0.1 - User is not able to navigate to "Saving your lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#603]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on "START" and select few motifs.
4: Add / skip the music and proceed to "Create" screen.
5: Export the lomotif.
6: Tap on "Make Lomotif" button on "Saving your Lomotif" screen. (User will navigated to "Share screen)
7: Observe there is no back option to navigate back to "Saving your Lomotif" screen.
8: Tap on back key (hard key).
9: Check if user is navigated back to "Saving your Lomotif" screen.

Expected result:
1: Back option should be displayed on "Share screen".
2: User should be navigated back to "Saving your Lomotif" screen by tapping back key (hard key).

Actual result: "Saving your Lomotif" screen flashes and user navigates to "Home" screen after tapping on back key (hard key) from "Share" screen.

**Comment by ayaadel87** [comment]
i can reproduce this bug on sony z2/6.0.1/ for build 1.6.0-r6 (66)
