### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Keypad is overlapping on "Make Lomotif" button on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#604]
Frequency: Every time

Action:
1: Launch the app.
2: Sing in with valid credentials.
3: Tap on "START" and create lomotif with few motifs.
4: Export the lomotif.
5: Tap on "Say something about this Lomotif" text box. (Keypad will appears)
6: Check if keypad is overlapping on "Make Lomotif" button.

Expected result: 
1: Keypad should not overlap on "Make Lomotif" button.
2: Keypad should get disappear when use taps anywhere on the screen outside the "Say something about this Lomotif" text box.

Actual result: Keypad is overlapping on "Make Lomotif" button on "Saving your Lomotif" screen.

Refer screenshot for more details

**Comment by testershub** [comment]
![keypad_overlap](https://cloud.githubusercontent.com/assets/18608449/20337275/18a556fc-abf6-11e6-866a-470ea24496cd.jpg)

**Comment by Dipamit** [comment]
@xiuie : Issue is partial reproducible on Nexus 6/7.0.
             1. Keypad is not disappear while tapping anywhere on the screen outside the "Say something about this Lomotif" text box.
             2. Keypad is not overlap on Make Lomotif.

=> Issue is reproducible on Xiaomi RedMi Note 3/5.1.1
1. keypad is not disappear and keypad is overlap.

**Comment by xiuie** [comment]
Dev says: tagging as android limitation. since button is at the bottom of the screen and the caption field has multiple lines, keyboard will always cover the button until user press back button to hide it
