### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Location icon is not functional on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#605]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on "START" and create lomotif with few motifs.
4: Export the lomotif.
5: Tap on location icon in "Say something about this Lomotif" text box.
6: Check if location icon is functional or not.

Expected result: Location icon should be functional on "Saving your Lomotif" screen.

Actual result: Location icon is not functional on "Saving your Lomotif" screen.

Refer screenshot for more details.

**Comment by testershub** [comment]
![location_icon](https://cloud.githubusercontent.com/assets/18608449/20337396/e643e290-abf6-11e6-8f4a-dd98f346b0e1.jpg)

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on Nexus 6/7.0 for build 1.6.0-r4(64)

**Comment by ayaadel87** [comment]
i'm able to reproduce this bug on /Sony Z2/6.0.1 for build [1.6.0-r6 (66)
