### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - User is not able to navigate "Sign Up / Sign In" screen after tapping on back key (hard key) from "Home" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#606]
Frequency: Every time

Action:
1: Launch the app.
2: Sign in with valid credentials.
3: Tap on "Setting" and logout from the account.
4: Tap on back key (hard key). (User will navigated to "Home" screen)
5: Again tap on back key (hard key).
6: Check if user is navigated to "Sign Up / Sign In" screen.

Expected result: User should be navigated to "Sign Up / Sign In" screen after tapping on back key (hard key) from "home" screen.

Actual result: Application is closing after tapping on back key (hard key) from "Home" screen.

Note: It is working as expected when user logout and tap on "back key (hard key) form screen after "Sign Up".

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 for build 1.6.0-r4(64)
