### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user minimize the app while "Sign up".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#607]
Frequency: Every time

Action:
1: Launch the app.
2: Enter valid email and password.
3: Tap on "Sign Up" button.
4: Enter valid username and tap on "Let's Go" button.
5: Immediately minimize the app.
6: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user minimize the app after tapping on "Let's Go" button while "Sign Up".

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwZmNSMHFUREMzUVU

**Comment by testershub** [comment]
@xiuie Application is freezing on "Sing In" screen when user minimize the app while "Sign In".

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce above issue and commented issue on Xiaomi RedMi Note 3/5.1.1 for build 1.6.0-r4(64)

**Comment by testershub** [comment]
@xiuie Similar issue is observed on "Recover Password" screen.
Application is crashing when user taps on "Recover" button and minimize the app.

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
