### ISSUE TITLE
[1.6.0-r4(64)] Nexus 6/7.0 Music starts automatically when maximize application.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-android-issues#608]
Frequency : Everytime

1. Open application and tap on start.
2. Select any image or video and tap on Next.
3. Select music from Find Music and tap on Next.
4. On Preview screen tap on Export.
5. After export process complete, Minimize application.
6.  open application and check if Music starts or not.

Expected result: Music should not start playing.

Actual result: Music starts playing while open application.

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

Please see, Similar issue is observed on "Share your Lomotif" screen.

**Comment by Dipamit** [comment]
@xiuie : On performing above steps on Xiaomi RedMi Note 3/5.1.1, page navigate to Home screen.

[2016_11_16_15_49_25.zip](https://github.com/Lomotif/lomotif-android-issues/files/594301/2016_11_16_15_49_25.zip)

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r16 (76)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.
Music is audible on "Share" screen when user minimize and maximize the app.

**Comment by Dipamit** [comment]
@xiuie: Verified, Resolved for build 1.6.0-r16(76)

Device: Xiaomi RedMi note 3/5.1.1 
            Nexus 6/7.0
