### ISSUE TITLE
[1.6.0-r4 (64)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Endless loading is displayed when user loads recently exported lomotif in offline mode.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#610]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Skip for now".
3: Tap on "START" and select few motifs.
4: Add music from "Find Music" tab and proceed to "Create" screen.
5: Export the lomotif (User will navigated to "Saving your Lomoitf" screen)
6: Tap on back key (hard key). (User will navigated to "Create" screen)
7: Tap on "Home >> Yes" option.
8: Kill the app.
9: Turn off the internet connection and launch the app.
10: Tap on "Settings >> clear cache".
11: Load the recently exported lomotif.
12: Check if warning message "Assets missing" is displayed.

Expected result: Warning message "Assets missing" should be displayed when user loads the recently exported lomotif in offline mode.

Actual result: Endless loading is displayed when user loads recently exported lomotif in offline mode.

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on Nexus 6/7.0 for build 1.6.0-r4(64)
