### ISSUE TITLE
Signup page details are not displaying when the user tap on the "signup for cloudflare" link.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#62]
Steps to reproduce:
1.Launch the application.
2.In "Get started" page tap on "settings" button.
3.Tap on the "Frequently asked questions" link.
4.Tap on the "email protected" link.
5.Tap on the "sign up for cloudflare" link.
6.Check whether signup page content are displaying or not.

Excepted result:The signup page details should display when the user tap on the "signup for cloudflare" link.

Actual result:Signup page details are not displaying when the user tap on the "signup for cloudflare" link.

Environment: Micromax P480/ android 5.0.1 
![signup](https://cloud.githubusercontent.com/assets/12474351/14274676/5e11573a-fb30-11e5-8e18-17d5d41fea57.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1
