### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S6 / 6.0.1 - Application is crashing when user try to sign up using existing email id.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#623]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "User" icon for login option.
3: Tap on "Login" option and try to sign up already exist "Email id".
4: Tap on "Sign up" button and proceed to "Username" screen.
5: Enter valid "Username" and tap on "Let's go!" button.
6: Check if application is crashing.

Expected result: Application should not crash and should show "Already exist email id" message. 

Actual result: Application is crashing when user try to sign up using existing email id.

**Comment by ayaadel87** [comment]
i can reproduce this bug on sony z2(6.0.1) for build 1.6.0-r9 (69

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].
