### ISSUE TITLE
"Subscribe to update" button is not working.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#63]
Steps to reproduce:
1.Launch the application.
2.In "Get started" page tap on "settings" button.
3.Tap on the "Frequently asked questions" link.
4.Tap on the "email protected" link.
5.Tap on the "Signup for cloudflare" link.
6.Tap on the "Privacy & Security" link.
7.Tap on the "support link".
8.Tap on the "click here to subscribe to continuous updates" link.
9.Tap on the "Subscribe to updates" button.
10.check whether the "subscribe to updates" button is working or not.

Excepted result: subscribe to update button should work.

Actual result: "Subscribe to update" button is not working.

Environment: Micromax P480/ android 5.0.1 
![subscribe](https://cloud.githubusercontent.com/assets/12474351/14275284/0cbabbfc-fb34-11e5-8805-e06d044fbff0.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1
