### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy S6 / 6.0.1 - Music is playing on "Share" screen when user navigate back to "Share" screen from "Instagram" sharing.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#632]
Frequency: Every time

Action:
1: Launch the app.
2: Login with valid credentials.
3: Tap on "START" and create lomotif with few motifs and add music.
4: Tap on "Export" option.
5: Tap on "Make Lomotif"  button. (User will be navigated to "Share" screen)
6: Tap on "Instagram" option. (User will be navigated to "Instagram" screen)
7: Tap on back option "<-". (User will be navigate back to "Share" scree)
8: Check if music is playing in background on "Share" screen.

Expected result: Music should not play on "Share" screen when user navigate back to "Share" screen from "Instagram" sharing.

Actual result: Music is playing on "Share" screen when user navigate back to "Share" screen from "Instagram" sharing.

**Comment by Dipamit** [comment]
[1.6.0-r9 (69)] Xiamo
I Note-3/ 5.1.1- Able to reproduce this issue.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

Music is audible when user navigates back to "Share" screen from "Instagram" sharing screen.
