### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - "Saving your Lomotif" progress stuck at 0% on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#634]
Frequency: Every time

Action:
1: Launch the app.
2: Login with valid credentials.
3: Tap on "START" and select few motifs / videos.
4: Skip the music and proceed to "Create" screen.
5: Delete all the added assets and tap on "Export" option.
6: User will be navigated to "Saving your Lomotif" screen.
7: Tap on "Make Lomotif" button.
8: Check if exporting stuck at 0%.

Expected result: Warning message "There are no clips" should be displayed when user try to export the lomotif which has no assets in it.

Actual result:
1: User is navigated to "Saving your Lomotif" screen when user tap on "Export" option even when there is no any assets in the lomotif.
2: Exporting stuck at 0%.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwb2xOX09PSXFyaVE

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Not able to reproduce for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1. 
Warning message "There are no clips in the project" is displayed when user export the lomotif which has no assets.
