### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Profile picture icon is not displayed to the user.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#636]
Frequency: Every time. 

Precondition:
- User should should be logged in to the application.

Actions: 
1: Launch the application.
2: Tap on "Profile view" icon to navigate to profile view screen.
3: Check if "Profile Picture" option is displayed to the user. 

Expected result: "Profile Picture" option should be displayed to the user so that user can tap on the icon and set the desired profile picture.  

Actual result: "Profile Picture" option is not displayed to the user. 

Note:
- Please refer the attached screenshot for more details.

**Comment by testershub** [comment]
![profile_pic](https://cloud.githubusercontent.com/assets/18608449/20455182/8a454132-ae7b-11e6-80b3-228dcb03b161.jpg)

**Comment by ayaadel87** [comment]
@xiuie : i think this is not a bug, since the user didnot choose yet Picture

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r16 (76)].

**Comment by Dipamit** [comment]
@xiuie : Verified. Resolved for version 1.6.0-r16 (76)
