### ISSUE TITLE
Alignment of text in body of "Frequently asked questions" page is not correct.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#64]
Steps to reproduce:
1.Launch the application.
2.In "Get started" page tap on "settings" button.
3.Tap on the "Frequently asked questions" link.
4.Tap on the "email protected" link.
5.Tap on  "Signup for cloudflare" link.
6.Tap on "Privacy & Security" link.
7.Check whether all the content is align properly or not.

Expected result: All the content should align in the proper way.

Actual result: The content are not align in the proper manner.

Environment: Micromax P480/ android 5.0.1 
![alignment](https://cloud.githubusercontent.com/assets/12474351/14279320/4a3c31ca-fb4a-11e5-8b0d-a6f7094e50aa.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.0.14] on Asus Zenfone Go 4.5 / Android 5.1
