### ISSUE TITLE
[1.6.0-r9 (69)] -  "Start Now" button in confirmation email is not functional.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#641]
Frequency: Every time

Action:
1: Launch the app.
2: Sign up with valid credentials.
3: Enter valid username and tap on "Let's Go" button.
4: Navigate to registered email account and open confirmation email.
5: Click on "Start Now" button.'
6: Check if "Start Now" button is functional.

Expected result: "Start Now" button in confirmation email should be functional.

Actual result: "Start Now" button in confirmation email is not functional.

Refer screenshot for more details:

**Comment by testershub** [comment]
![start now](https://cloud.githubusercontent.com/assets/18608449/20455234/15ad3c2e-ae7d-11e6-9d32-e22b8ccc9f39.jpg)

**Comment by ayaadel87** [comment]
@xiuie : i can reproduce this bug on sony z2(6.0.1) for build

but in my email, start button is not clickable and not displayed as button 1.6.0-r9 (69
check  
![untitled](https://cloud.githubusercontent.com/assets/23448116/20462033/51f1bf80-af21-11e6-9f86-212374a50ae0.png)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue.
