### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy S6 / 6.0.1 - "Log In" button is not functional when user minimize the app while login.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#642]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on user icon >> Login button.
3: Tap on "Sign In" option.
4: Enter valid credentials and tap on "Log In" button.
5: Minimize the app.
6: Relaunch the app.
7: Observed user stay on "Login" screen.
8: Tap on "Log In" button.
9: Check if "Log In" button is functional or not.

Expected result: User should navigate to "Home" screen when user minimize the app after tapping on "Log In" button.

Actual result:
1: User remains on "Log In" screen after tapping on "Log In" button.
2: "Log In" button is not functional when user minimize and relaunch the app while login.

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwU1JldlltSEVIQzg

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S6 / 6.0.1.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r23 (83)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.0.3-r8 (99)] on Google Pixel / 7.1.1.
