### ISSUE TITLE
[1.6.0-r9 (69)/Sony z2(6.0.1) /saved Lomotif is not playing correctly

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#643]
Frequency: Every time
Precondition: there are already saved Lomotif

Steps:

- launch the app
- enter valid username and password
- press on Account icon(under start in home page) 
- press on lomotif tab
- select any Lomotif and press on it

Expected Result:
Lomotif is played successfully
Actual Result:
Lomotif is not played successfully and no music is playing

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

**Comment by Dipamit** [comment]
@xiuie : Verified, Resolved for build 1.6.0-r16(76) on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.1

Note:  Lomotif taking too much time for loading, even device is off, video starts playing.

**Comment by ayaadel87** [comment]
@xiuie : i still can reproduce this issue for build 1.6.0-r23
