### ISSUE TITLE
[1.6.0-r9 (69)/Sony z2(6.0.1)/Lomotif is not saved to gallery

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#644]
Frequency: Every time
Steps:

- launch the app
- sign in with valid user name and password
- press on start button
- select any image and music 
- click on export 
- type any text and press on make lomotif

note: make sure that" saved to gallery check box" is checked

expected Result:
Lomotif is saved to  telephone gallery

Actual Result:
Lomotif is not saved to telephone gallery

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

Exported lomotif does not save to Lomotif-staging folder at camera roll folder

**Comment by testershub** [comment]
@xiuie Duplicate of #558

**Comment by Dipamit** [comment]
@xiuie: I can reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r16(76)

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by ayaadel87** [comment]
@xiuie :I can still reproduce this issue for build [1.6.0-r22 (82) on sony z2(6.0.1)

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

Issue is reproducible even when user is logged in or logged out

**Comment by ayaadel87** [comment]
@xiuie : can still reproduce this issue for build [1.6.0-r22 (82) on sony z2(6.0.1)

**Comment by xiuie** [comment]
Reproducible on [1.6.0-r22 (82) on Lomo.HW (kyocera)

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r23(83)]
