### ISSUE TITLE
[1.6.0-r9 (69)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 2 / 6.0.1 - "Email" and "Password" icons are not displayed on "Username" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#653]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "User" icon.
3: Enter valid email and password and tap on "Sign Up" button.
4: Check if "Email" and "Password" icons are displayed in respective fields.

Expected result: "Email" and "Password" icons should be displayed in respective fields on "Username" screen.

Actual result: "Email" and "Password" icons are not displayed on "Username" screen.

Refer screenshot for more details:

**Comment by testershub** [comment]
![icons](https://cloud.githubusercontent.com/assets/18608449/20521334/c1f4b7e6-b0d0-11e6-8ac7-d603eb88bb69.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
