### ISSUE TITLE
[1.6.0-r16 (76)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - Recently exported lomotif is not displayed on "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#654]
Frequency: Every time.

Precondition: User should be logged in to the app.

Action:
1: Launch the app.
2: Tap on "Start" button and create and export a lomotif by adding some images/motifs.
3: Tap on "No thanks, I'll share later" option.
4: Navigate to the profile view >> "Lomotifs" tab.
5: Check if recently created and exported lomotif is displayed in "Lomotifs" tab.

Expected result: Recently exported lomotif should be displayed in "Lomotifs" tab.

Actual result: Recently exported lomotif should be displayed in "Lomotifs" tab.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build 1.6.0-r16 (76) on Asus Zenfone Go / Android 5.1

Created and exported Lomotif is displayed in Lomotif tab

**Comment by ayaadel87** [comment]
@xiuie : i can reproduce this issue for build v1.6.0-r22 (82) on sony z2(6.0.1)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r27 (87)] on Samsung Galaxy Note 4 / 6.0.1
