### ISSUE TITLE
[1.6.0-r16 (76)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - Confirmation message informing the user that the password has been changed successfully is not displayed. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#656]
Frequency: Every time.

Precondition: User should be logged in to the application.

Action:
1: Launch the app.
2: Swipe up to reveal profile view.
3: Tap on "Settings" icon >> "Password". 
4: Enter valid information in the text fields and tap on "Save" icon.
5: Check if confirmation message informing the user whether or not the password was updated successfully is displayed.

Expected result: "You have changed your password" confirmation message should be displayed to the user.

Actual result: "You have changed your password" confirmation message is not displayed to the user.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.6.0-r16 (76) on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

Confirmation message "You have changed your password" is not displayed after changing password.

**Comment by xiuie** [comment]
Oops. Sorry. This is works as designed. We will no longer have password confirmation dialogue.
