### ISSUE TITLE
[1.6.0-r16 (76)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - "Home" button is not displayed on "Profile view".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#658]
Frequency: Every time.

Precondition:
- User should be logged in to the application.
- There should exist 2-3 saved projects. 

Action:
1: Launch the application.
2: Navigate to the profile view.
3: Check if "Home" button is displayed in both "In progress" and "Lomotifs" tab.

Expected result: "Home" button should be displayed clearly to the user.

Actual result: "Home" button is not displayed in the profile view. 

Note:
- Please refer the attached screenshot for more details.
![home](https://cloud.githubusercontent.com/assets/18608449/20620612/896c1516-b320-11e6-8c99-c659a012a1d4.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can't exactly  reproduce this issue for build 1.6.0-r16 (76) on Asus Zenfone Go / Android 5.1

Home button is available at the bottom of the screen. But it is in white / light color, so it's not clearly visible

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
