### ISSUE TITLE
[1.6.0-r16 (76)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - User is getting logged out of the application in offline mode. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#659]
Frequency: Every time.

Precondition:
- User should be logged out of the application.

Action: 
1: Launch the application.
2: Navigate to "Profile View" screen.
3: Login with valid credentials. 
4: Kill the application and put the device on offline mode.
5: Reboot the app and check if user is getting logged out of the application.

Expected result: User should not get logged out of the application in offline mode.

Actual result: User is getting logged out of the application in offline mode.

Note:
- Please refer the following video link for more details:
 https://drive.google.com/open?id=0ByjueaPWc0dwdXJZd1B3REM3ME0

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.6.0-r16 (76) on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
