### ISSUE TITLE
[1.6.0-r16 (76)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy Note 2 / 4.4.2 - Irrelevant confirmation message is displayed after uploading the profile picture.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#660]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on profile picture icon.
3: Tap on "Change profile picture" option.
4: Select 1 image form gallery.
5: Check if relevant confirmation message is displayed.

Expected result: Relevant confirmation message "Profile picture upload successfully" should be displayed after updating / changing the profile picture.

Actual result: 
1: Irrelevant confirmation message "Profile picture failed to upload..." is displayed after uploading profile picture. 
2: Profile picture is getting changed / updated successfully.

Refer screenshot for more details:

Note: Please see, continuous loading is displayed when user upload / change profile picture in offline mode.

**Comment by testershub** [comment]
![profile_picture](https://cloud.githubusercontent.com/assets/18608449/20624884/8a0c35a4-b335-11e6-9c0d-2fcb9a535912.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.6.0-r16 (76) on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
