### ISSUE TITLE
[1.6.0-r18 (78)] Asus Zenfone Go / Android 5.1 - User can login with username - Enter username instead of Email on Sign in page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#661]
Frequency: Every time

Action:
1. Launch the app.
2. On Sign up page, tap on Sign in option
3. There will be "Email" and "Password" field available on Sign in page
4. Enter valid (already registered) username instead of Email
5. Enter valid registered password
6. Check whether user is able to login with username instead of Email in Email field

Expected result: User should be able to login only with Email as there is "Email" field given

Actual result: User can also login by entering username in Email field.

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

**Comment by xiuie** [comment]
This is expected behavior

**Comment by hiteshbheda** [comment]
@xiuie Thanks! But I think in caption  it should mention like Email / Username. So user can have better idea about login flexibility.
