### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy S6 / 6.0.1 - Display name is overlapping on "About Me" text on profile view.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#662]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Settings >> Display name".
3: Enter display name till the end of the field (till max length)
4: Tap on tick to save the display name and navigate to profile view.
5: Check if display name is overlapping on "About Me" text.

Expected result: Display name should not overlap on "About Me" text on profile view.

Actual result: Display name is overlapping on "About Me" text on profile view.

Refer screenshot for more details:

**Comment by testershub** [comment]
![overlapping](https://cloud.githubusercontent.com/assets/18608449/20699737/e6d7f808-b62e-11e6-923c-dca493dc8c03.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
