### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy S6 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing while sharing lomotif via Facebook.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#665]
Frequency: Every time

Precondition: User should be logged out.

Action:
1: Launch the app.
2: Tap on "START" and create lomotif with few motifs with / without music.
3: Tap on "Export" option.
4: Tap on "Facebook" option on "Share" screen.
5: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing while sharing lomotif via Facebook.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iYnhDbWpiQUhHVG8

**Comment by testershub** [comment]
@xiuie Please see, user is not able to share the lomotif with all sharing options as "Instagram", "Messenger", "Email" etc.
Issue is specifically observed when user is not logged in. It is working as expected when user is logged in.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

Different responses for Facebook, Instagram, Messanger and Text message are as display in attached image:

![1](https://cloud.githubusercontent.com/assets/9691390/20714935/91b1fb36-b673-11e6-90c8-ac4f5417d99b.png)

![screenshot_2016-11-29-14-11-20](https://cloud.githubusercontent.com/assets/9691390/20714932/91a980a0-b673-11e6-89b3-f2fab41adb4b.png)

![screenshot_2016-11-29-14-11-29](https://cloud.githubusercontent.com/assets/9691390/20714934/91ab31a2-b673-11e6-9588-d4506be950af.png)

![screenshot_2016-11-29-14-11-52](https://cloud.githubusercontent.com/assets/9691390/20714933/91ab5ca4-b673-11e6-8f2a-8b590820f393.png)

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

Please see, issue is reproducible while sharing lomotif via "Text Message". For other sharing options it is working as expected.

Refer following screenshot for more details:
![share_text_msg](https://cloud.githubusercontent.com/assets/18608449/20827218/760e11ec-b896-11e6-8d51-6a9cbf54ee9c.png)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r23 (83)] on Asus Zenfone Go / Android 5.1
