### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user refresh the "Lomotifs" tab and taps on "Home" option.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#666]
Frequency: Every time

Precondition: User should not have any lomotif under "Lomotifs" tab.

Action:
1: Launch the app and login with valid credentials.
2: Tap on user icon to navigate profile view.
3: Tap on "Lomotifs" tab and pull down the screen to refresh the screen.
4: Tap on "Home" icon when screen is refreshing.
5: Check if application is crashing.

Expected result: Application should not crash when user refresh "Lomotifs" tab and taps on "Home" option.

Actual result: Application is crashing when user refresh the "Lomotifs" tab and taps on "Home" option.

Note: Similar issue is observed when user is not logged in.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ib1M0bmJtcnVFa1U

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
