### ISSUE TITLE
[1.6.0-r18 (78)] Asus Zenfone Go / Android 5.1 - "Updating profile" never ends - Change username

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#667]
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential
3. Go to user profile page
4. Click on username to change username
5. Enter username which is already registered and click on Ok tick sign
6. Check whether user get any error / warning message or not

Expected result: User should get Error / Warning message like "username already exist"

Actual result: 
1. User does not get any Error / Warning message
2. "Updating profile" process starts and never ends

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Samsung Galaxy Note 4 / 6.0.1 and Samsung Galaxy S4 / 5.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

Works properly with alert message
