### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Irrelevant message "Oops, something went wrong..." is displayed when user refresh "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#668]
Frequency: Every time

Precondition: User should not be logged in.

Action:
1: Launch the app.
2: Tap on user icon to reveal profile view.
3: Tap on "Lomotifs" tab and observe "Sign up or log in to store your Lomoitfs forever!" message is displayed.
4: Pull down the screen to refresh the screen.
5: Check if irrelevant message "Oops, something went wrong..." is displayed.

Expected result: Relevant message "Sign up or log in to store your Lomoitfs forever!" should be displayed under "Lomotifs" tab when user is not logged in.

Actual result: Irrelevant message "Oops, something went wrong..." is displayed when user refresh "Lomotifs" tab.

Refer screenshot for more details:

**Comment by testershub** [comment]
![oops_lomotif tab](https://cloud.githubusercontent.com/assets/18608449/20705190/007235b2-b648-11e6-8055-a1e3f68ab22b.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
