### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Continuous loading is displayed while changing profile picture.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#671]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Turn off the internet connection.
3: Tap on user icon to reveal profile view.
4: Tap on profile picture  and select 1 image.
5: Warning message "Profile picture uploading failed. Please check internet connectivity"will be displayed.
6: Tap on "OK" option on warning message.
7: Check if continuous loading symbol is displayed.

Expected result: Continuous loading symbol should not be displayed when user changes profile picture in offline mode.

Actual result: Continuous loading symbol is displayed when user changes profile picture in offline mode.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r2  (82)] on Samsung Galaxy S4 / 5.0.1.

Warning message "Profile picture failed to upload. Check your your phone connectivity" is displayed on Samsung Galaxy Note 4 / 6.0.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r23 (83)] on Asus Zenfone Go / Android 5.1

When user click on "OK" button on "Profile picture failed to upload. Check your phone connectivity.", User navigates to user profile view. Works properly.
