### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing when user taps on "Lomotifs" tab and "Home" option.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#675]
Frequency: Every time

Action: 
1: Launch the app and login with valid credentials.
2: Tap on user icon to reveal profile view.
3: Tap on "Lomotifs" tab and immediately tap on "Home" option.
4: Repeat step-2 and step- 3 more than 2 times.
5: Check if application is crashing.

Expected result: Application should not crash when user taps on "Lomotifs" tab and "Home" option.

Actual result: Application is crashing when user taps on "Lomotifs" tab and "Home" option.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iQkNDZkZmQVpna0U

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by ayaadel87** [comment]
@xiuie :I can't reproduce this issue for build [1.6.0-r18 (78)] on sony z2(6.0.1)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r27(87)] on Samsung Galaxy J7 (6.0.1)
