### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Application is crashing while deleting lomotif under "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#678]
Frequency: Every time

Precondition: There should be at least 1 lomotif under "Lomotifs" tab.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Lomotifs" tab and load the lomotif.
3: Tap on menu option (three dots) and tap on "Delete" option.
4: Tap on "OK" option on confirmation pop up.
5: Immediately tap on "Home" option.
6: Check if application is crashing.

Expected result: Application should not crash when user deletes the lomotif and navigates to "Home" screen.

Actual result: Application is crashing when user deletes the lomotif and immediately taps on "Home"  option.

Refer following video link for more details: 
https://drive.google.com/open?id=0B0-oVt0Gfy3ibVRvQ2hZTmZMa1k

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
