### ISSUE TITLE
Lomotif video is not exporting to the messenger.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#68]
Steps to reproduce:
1.Launch the application.
2.select any created lomotif video.
3.Tap on the export on the top right corner.
4.Export the lomotif video with the messanger.
5.check whether the video is exporting or not.

Expected result:Lomotif video should export to the messenger.

Actual result: Lomotif video is not exporting to messenger.

Environment: Micromax P480/ android 5.0.1 

![msg1](https://cloud.githubusercontent.com/assets/12474351/14280932/a03c402a-fb53-11e5-94cb-b2cf20147324.png)

![msg2](https://cloud.githubusercontent.com/assets/12474351/14280891/5ae44680-fb53-11e5-8173-c37fa92291fc.png)

**Comment by jpaulo1205** [comment]
@vinay97t hi, this only happens when you have not selected any recipient for the message. (messenger should have returned a list of your friends where you can select to whom you want to send the video, otherwise the send button will be disabled)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this issue for build [1.0.14] on Sony xPeria Z / Android 5.1.1

It works correctly. Without selecting recipient there should no active submit button.

**Comment by kcherkas** [comment]
@xiuie @jpaulo1205 yes,  this only happens when no recipient for the message were selected. It is correct behavior. Not a bug.
