### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Nexus 5 / 6.0.1 - "Home" option on "In Progress" and "Lomotifs" tab is not working as expected.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#682]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create lomotif with few motifs.
3: Tap on "Export >> Make Lomotif".
4: Skip sharing and navigate to "In Progress / Lomotifs" tab.
5: Wait till uploading finish.
6: Tap on "Lomotif Uploaded" from "Notification" screen.
7: User will be navigated to "In Progress" tab.
8: Tap on "Home" option.
9: Check if user is navigated to "Home" screen.

Expected result: User should be navigated to "Home" screen after tapping first time on "Home" option from "In Progress / lomotifs" tab.

Actual result: 
1: User is not navigated to "Home" screen after tapping on "Home" option from "In Progress / lomotifs" tab for first time.
2: It is working as expected when user taps on "Home" option for second time.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
