### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy Note 4 / 6.0.1, Samsung Galaxy S4 / 5.0.1 - Keypad is not disappearing when user navigate to "Sign In" screen from "Recover" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#683]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Sign In" option.
3: Tap on "Forgot Password?".
4: Tap text field on "Recover" screen. (Keypad will be appeared)
5: Tap on back option "<".
6: Check if keypad is disappeared.

Expected result: Keypad should disappear when user navigate to "Sign In" screen from "Recover" screen.

Actual result: Keypad is not disappearing when user navigate to "Sign In" screen from "Recover" screen.

Refer attached screenshot for more details:
![keypad](https://cloud.githubusercontent.com/assets/18608449/20748029/98b0b8ba-b712-11e6-8a9b-635f4143a51f.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
