### ISSUE TITLE
[1.6.0-r18 (78)] Samsung Galaxy S4 / 5.0.1, Samsung Galaxy Note 4 / 6.0.1 - User is not able to delete lomotif under "Lomotifs" tab in offline mode.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#684]
Frequency: Every time

Precondition: User should have upload at least one lomotif. 

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Lomotifs" tab and load any lomotif.
3: Turn off the internet connection. 
4: Tap on menu option (three dots) and tap on "Delete" option.
5: Tap on "OK" option on confirmation option.
6: Check if user is bale to delete the lomotif.

Expected result: Relevant error message "Please connect Wi-Fi or mobile data to access this" should be displayed when user try to  delete the lomotif in offline mode.

Actual result: Irrelevant error message "Oops, something went wrong.." is displayed when user try to delete lomotif in offline mode.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**But I think it works as design because without internet lomotif should not be deleted from "Lomotif" tab from specific user account.**

**Comment by testershub** [comment]
@xiuie Verified. Issue is resolved for version [1.6.0-r22(82)].
