### ISSUE TITLE
[1.6.0-r18 (78)] Asus Zenfone Go / Android 5.1 - Sync not working - Change username, caption, username, profile pic in iOS app and not updated in Android app

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#686]
Frequency: Every time

Action:
1. Launch the app in iOS device
2. Login with valid credentials in iOS device
3. Go to profile information page
4. Change Profile picture, username, caption in iOS app
5. Now launch app in android device
6. Login with the same credentials which is used in iOS for change details
7. Check on user profile page whether all changed details in iOS app have been updated in android app or not

Expected result: Changed details like profile picture, username, caption should be synched and updated in android app

Actual result: Profile picture, username, caption not changed / synched in android device app

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go/ Android 5.1

**Comment by testershub** [comment]
@xiuie I am facing following two issues while performing above steps for build [1.6.0-r18 (78)] on Samsung Galaxy Note 4 / 6.0.1 :

1: Profile information is not displayed on "Profile View" screen.
2: Continuous loading is displayed on Android device after tapping on "Settings" option.

Refer following screenshot for more details:
![blank_profile](https://cloud.githubusercontent.com/assets/18608449/20823547/0b66863c-b87b-11e6-9a7d-00aa88af1ee6.png)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

This issue has been resolved.

Close this issue for build [1.6.0-r22 (82)]
