### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Video not added - create lomotif using video and add song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#7]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any videos from video folder from My Video tab
4. Select any song from Find Music tab
5. Play lomotif

Expected result: Lomotif should be played with audio and video

Actual result: Lomotif does not contain video and audio

**Comment by xiuie** [comment]
@hiteshbheda Does this happen on multiple Android devices?

**Comment by xiuie** [comment]
@paulyangzhiwen Need a charged android device to try replicating some of these.

**Comment by hiteshbheda** [comment]
@xiuie sir i have only one android device now as in another two devices, app does not support because of down version of android OS

**Comment by xiuie** [comment]
@hiteshbheda can you try different file types and @jpaulo1205 thinks that this might be a file codec issue.

**Comment by jpaulo1205** [comment]
@hiteshbheda can also provide a recording of the issue? and possibly list of the video formats you've used, as xiu mentioned, it might be a codec issue. thanks

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I'm attaching video for this. Now it supports some time and some time it gets error.

Please find attached video.

https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UVlNSZUlTM2hSWlE

**Comment by jpaulo1205** [comment]
@hiteshbheda sorry just checked. can you give open permission to the link? I can't access it. thanks

**Comment by hiteshbheda** [comment]
@jpaulo1205 Hi. I have made it open access now. Now please check it. 

Let me know still you need my help.

**Comment by jpaulo1205** [comment]
@hiteshbheda thanks! I just saw the video, can you replicate it again and this time, press the REPORT button? Need to see the crash log to determine the exact cause of the issue. Thanks!

**Comment by hiteshbheda** [comment]
@jpaulo1205 Sure. I'll try to replicate it again by following mentioned steps. I'll intimate you.
Thanks!

**Comment by hiteshbheda** [comment]
@jpaulo1205 I can still replicate it. sometimes during playing lomotif and sometime during Exporting it.

I have sent you a REPORT from my android phone for this issue.

**Comment by jpaulo1205** [comment]
@hiteshbheda  thanks!

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can replicate this same critical issue for Build version [1.0.14] on Sony xPeria Z / Android 5.1.1.

I don't know the problem. But it may be because of Unsupported video format.

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.0.18 on Asus Nexus 7 Android 5.1.1
