### ISSUE TITLE
[1.6.0-r23 (83)] Samsung Galaxy J7 / 6.0.1, Samsung Galaxy Tab S2 / 6.0.1 - Error message: "Oops, something went wrong..." is displayed on "Make Lomotif" button while exporting lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#701]
Frequency: Every time

Action:
1: Launch the app and log in with valid credential.
2: Create lomotif with minimum 10 video from camera roll and proceed to "Create" screen with/without music.
3: Tap on export option, user will be navigated to "Saving your Lomotif" screen.
4: Wait for few secs on "Saving your Lomotif" screen.
5: Check if error message: "Oops, something went wrong..." is displayed on "Make Lomotif" button.

Expected result: Error message: "Oops, something went wrong..." should not display on "Make Lomotif" button.

Actual result: 
1: Error message: "Oops, something went wrong..." is displayed on "Make Lomotif" button.
2: Button is tappable and after tapping on button, "Saving your Lomotif" progress getting stuck at 0% and never proceed.. 

Refer following video for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iVnJNeE5kWFhuaFE

**Comment by Dipamit** [comment]
@xiuie : Not able to reproducible on Xiaomi RedMi Note 3/5.1.1 for build 1.6.0-r23 (83)

**Comment by ayaadel87** [comment]
@xiuie :not able to reproduce this bug on sony z2 for build  1.6.0-r23 (83)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.6.0-r27 (87)] on Samsung Galaxy J7 (6.0.1)
