### ISSUE TITLE
[2.0.3-r7 (98)] Google Pixel / 7.1.1 - Irrelevant pop up message is displayed when user install and launch the app.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#733]
Frequency: Every time

Action:
1: Install and launch the app.
2: Check if irrelevant pop up message is displayed.

Expected result: Relevant pop up message should be displayed or relevant message should be displayed on the pop up.

Actual result: Irrelevant pop up message is displayed when user install and launch the app.

Refer screenshot for more details:
![pop up](https://cloud.githubusercontent.com/assets/18608449/21669556/d8bd7aba-d332-11e6-8fe4-465027df8562.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r7 (98)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by xiuie** [comment]
This is a test that will only appear in dev.
