### ISSUE TITLE
[2.0.3-r7 (98)] Google Pixel/ 7.1.1 - User profile is displayed as blank when user navigate to user's profile in offline mode.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#737]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "Search user" icon and search for any user.
3: Search result will be displayed.
4: Turn off the internet connection.
5: Tap on any user from search result.
6: Check if warning message is displayed or not.

Expected result: Warning message should be displayed when user navigate to user's profile in offline mode.

Actual result: User profile is displayed as blank when user navigate to user's profile in offline mode.

Refer following screenshot for more details:
![blank_profile](https://cloud.githubusercontent.com/assets/18608449/21670171/2151fd32-d338-11e6-9e00-42e7d93c9148.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r7 (98)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by xiuie** [comment]
Thanks for design feedback. Checked with Designer. Works as Designed.

**Comment by testershub** [comment]
@xiuie Ok.Noted. Thanks.
