### ISSUE TITLE
[1.0.14] Samsung Galaxy Grand Prime/5.0.2 - Unable to crop/resize an image from the timeline

### ISSUE THREAD

**Issue by archanaoswal** [Lomotif/lomotif-android-issues#74]
[1.0.14] Samsung Galaxy Grand Prime/5.0.2 - Unable to crop/resize an image from the timeline

Frequency: Every Time

Action:
1. Launched Lomotif
2. Click on start
3. Select few images
4. In music screen, tap on my music tab
5. Select a song
6. On the next screen (Create) tap thumbnail and try to resize by pinching and zoom,
7. Nothing happens

Expected Result: User should be able to crop/resize an image

Actual Result: Nothing happens

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue on Sony xPeria Z / Android 5.1.1.

But i think there is no bug in it. It works correctly as like an iOS app.

**Comment by xiuie** [comment]
@archanaoswal Sorry my mistake. Crop/resize not available yet in this build.
