### ISSUE TITLE
[1.0.13] LG Nexus 5X / Android 6.0.1 - My Video - Keyboard doesn't disappear when user taps close button on My Video screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-android-issues#8]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Tap on search field -> Keyboard appears
4. Tap close button on My Video screen

Expected result: User sees home screen without keyboard

Actual result: User sees home screen with opened keyboard

Video: [Keyboard.zip](https://github.com/Lomotif/lomotif-android-issues/files/175556/Keyboard.zip)

**Comment by jpaulo1205** [comment]
Note: Fixed for next build (1.0.14)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can replicate it every time on Sony xPeria Z / Android 5.1.1

**Comment by vysohanych** [comment]
@xiuie @jpaulo1205 Can't reproduce on build 1.0.14

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can't reproduce this in build [1.0.14] on Sony xPeria Z / Android 5.1.1
