### ISSUE TITLE
[2.0.3-r8 (99)] Samsung Galaxy Note 4 / 6.0.1 - Error message as "Oops, something went wrong, Please try again" is displayed when user cancel authorization for instagram.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#806]
Frequency: Everytime.

Action:
Precondition: User should have a new Instagram account which is not used or authorized for Lomotif app.
1: Launch the app and login with valid credentials.
2: Tap on "START" and tap on "Instagram".
3: Enter valid credentials and tap on "Log In" button.
4: Authorization pop up will be displayed and tap on "Cancel" button.
5: Check if error message is displayed.

Expected result: Error message as "Oops, something went wrong, Please try again" should not display when user cancel authorization for Instagram.

Actual result: Error message as "Oops, something went wrong, Please try again" is displayed when user cancel authorization for Instagram.

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r8 (99)] on Moto X Play / 6.0.1.

**Comment by xiuie** [comment]
Dev says this is works as designed
