### ISSUE TITLE
[2.0.3-r9 (100)] Samsung Galaxy Note 2 / 4.4.2 - Application is crashing when user export lomotif which is created by using "Dubsmash" app videos.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#836]
Frequency: Everytime.

Precondition: User must have "Dubsmash" app videos.

Action:
1: Launch the app and login with valid credentials.
2:  Create lomotif with "Dubsmash" app videos.
3: Add/skip music and export the lomotif.
4: Tap on "Make lomotif" button and tap on "I'm done. Thanks!"
5: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user export lomotif which is created by using "Dubsmash" app videos.

**Note: This issue is specifically observed for Samsung Galaxy Note 2 / 4.4.2**

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudN19FTHVOUHBJdUk

Please refer video link for more details:

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.0.3-r10 (101)] on Asus Zenfone Go / Android 5.1

Works properly

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r10 (101)] / Asus ZenFone 5 / 4.4.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.5-r5 (115)] on Asus Zenfone 5 / 4.4.2
