### ISSUE TITLE
[2.0.3-r10 (101)] Samsung Galaxy S6 / 6.0.1 - Continuous loading sign is displayed under "Featured" tab when user refresh the screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#839]
Frequency: Every time

Action:
1: Launch the app and login with valid credential.
2: Swipe right to reveal "Featured/Following" screen,
3: Navigate to "Following" tab and scroll down few lomotifs down.
4: Navigate to "Featured" tab, pull the screen to refresh and immediately tap on "Following" tab.
5: Scroll down the "Following" tab to load more lomotif and tap on "Featured" tab.
6: Check if continuous loading sign is displayed.

Expected result: Continuous loading sign should not be display under "Featured" tab.

Actual result: Continuous loading sign is displayed under "Featured" tab when user refresh the screen.

Refer following video link for more details:
 https://drive.google.com/open?id=0B0-oVt0Gfy3iQTNhUkdyZWFqUFU

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r10 (101)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.3-r10 (101)] on Google Pixel /7.1.1.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.5-r5 (115)] on Samsung Galaxy Note 4 / 6.0.1 and Moto X Play / 6.0.1
