### ISSUE TITLE
[1.0.15] Asus Zenfone Go 4.5 / Android 5.1 - Audio not available - Songs not available in Find Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#85]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few pictures from Camera folder in My Video category
4. Click on apply button and go to next screen for music
5. Tap on Find Music tab
6. Observe screen message

Expected result: Songs from Find Music tab should be displayed

Actual result: Error Message displayed "An error has occurred"

![screenshot_2016-04-06-09-10-55](https://cloud.githubusercontent.com/assets/9691390/14305333/edf4d2a2-fbd8-11e5-8b13-2a07ea7b2bc1.png)

**Comment by kcherkas** [comment]
Not reproducible at samsung galaxy S4, android 4.4.2

**Comment by xiuie** [comment]
@hiteshbheda Is this still occurring?

**Comment by hiteshbheda** [comment]
@xiuie No, I can't reproduce it now neither on Asus Zenfone nor on Sony xPeria Z.

**Comment by hiteshbheda** [comment]
@xiuie You can close this issue now. Please
