### ISSUE TITLE
[2.0.3-r10 (101)] Samsung Galaxy S6 / 6.0.1 - Preview is not playing smoothly when lomotif created with "Talking Tom" app videos.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-android-issues#860]
Frequency: Everytime.

Precondition: User must have installed "Talking Tom 2" app.

Action: 
1: Launch the app.
2: Tap on "START".
3: Select 2 "Talking Tom" videos from "Camera roll" tab.
4: Add/Skip music and navigate to "Create" screen.
5: Let the preview play.
6: Change timeline from 15 secs to 30 secs and let the preview play.
7: Check if preview is playing smoothly.

Expected result: Preview should play smoothly when lomotif created with "Talking Tom" app videos.

Actual result: 
1: Preview is not playing smoothly when lomotif created with "Talking Tom" app videos.
2: Preview is getting stuck in between and audio of second asset is audible.

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudd0FvcFM4S2tnR3M

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.3-r10 (101)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by Aboli-Testershub** [comment]
@xiuie This issue specifically observed for Samsung Galaxy S6 / 6.0.1.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.5-r5 (115)] on Samsung Galaxy S6 / 6.0.1 and Samsung Galaxy Note 4 / 6.0.1.
