### ISSUE TITLE
[2.0.4-r2 (106)] Samsung Galaxy Note 4 / 6.0.1 - Lomotif of unfollow user is not getting disappeared from "Following" tab when user unfollow the following user.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#919]
Frequency: Every time

Precondition:
- There should be some lomotif of following user under "Following" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe right and navigate to "Featured/Following" screen.
3: Navigate to "Following"  tab and select one lomotif of following user.
4: Tap on "Username" and navigate to profile screen of following user.
5: Unfollow the user and navigate back to "Following" tab.
6: Check if lomotif of unfollow user is getting disappeared or not.

Expected result: Lomotif of unfollow user should get disappear from "Following" tab.

Actual result: Lomotif of unfollow user is not getting disappeared from "Following" tab when user unfollow the following user.

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.4-r2 (106)] on Moto X Play / 6.0.1

**Comment by xiuie** [comment]
Works as designed for now. Everything works as expected upon pull to refresh.
