### ISSUE TITLE
[2.0.4-r2 (106)] Google Pixel / 7.1.1 - Application is crashing when user launch the app.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#926]
Frequency: Every time

Action:
Precondition: App "Storage" permission should be disable.
1: Navigate to device "Settings" and enable the storage permission.
2: Launch the app.
3: Check if application is crashing.

Expected result: Application should not crash when user launch the app after enable the storage permission.

Actual result: Application is crashing when user launch the app after enable the storage permission.

Please refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iR2QxUFRTa0t6cVk

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.4-r2 (106)] on Samsung Galaxy Note 4 /6.0.1

**Comment by xiuie** [comment]
Description:- Application is crashing when user launch the app.
Device reproducible on:- Samsung Galaxy Note 4 / 6.0.1
debug details:- Device ID: 6271b1e6-d9b4-45e4-84bb-9f500fc28f48R
ADID: 1f35e574-d47e-40fc-97ab-5c72c19e5ae2
Auth Key: 09aefc774172362f7e993e90bfd0535d6e03ac96

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.0.5-r6 (116)] on Google Pixel / 7.1.1.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.0.6-r2 (127)] on Moto X Play / 6.0.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.0.9-r2 (141)] on Samsung Galaxy S6 / 6.0.1
