### ISSUE TITLE
[1.0.15] Micromax P480/ android 5.0.1 -"Timing is same for "Instagram -15s" and "Lomotif- 30s" Videos.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#94]
Action:
1.Launch Lomotif.
2.Tap on "start" button.
3.Tap on the "type here to search motifs" text box.
4.Search and select any video.
5.select the music which you want to play with the video.
6. Tap on the "Instagram-15s" button and calculate the timing.
7.Now tap on "Lomotif- 30s" button and calculate timing.
8.Check whether the video timing is different or not.

Expected result:Video timing for "Instagram -15s" and "Lomotif- 30s" should be different. 

Actual result: Video timing for "Instagram -15s" and "Lomotif- 30s" is same.

![timing2](https://cloud.githubusercontent.com/assets/12474351/14316547/3a61ae24-fc21-11e5-8f34-af7e56110c71.png)

**Comment by xiuie** [comment]
@vinay97t Thanks. But we're replacing this in the next version.
