### ISSUE TITLE
[2.0.4-r2 (106)] Samsung Galaxy Note 4 / 6.0.1 - "Are you sure you want to proceed...." message is displayed even when user have selected the music from "My Music" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-android-issues#940]
Frequency: Every time

Action:
1: Launch the app and login with valid credential.
2: Tap on "START" and create lomotif with video/motif/pictures.
3: Proceed to "Find Music" screen and navigate to "Find Music" screen.
4: Tap on any music, music starts playing and then navigate to "Find Music" tab(Music will be still audible).
5: Search for any music and observed previous music will be stop playing.
6: Cancel search result and navigate to "My Music" tab(Previously selected music is still displayed as selected).
7: Tap on ">" option.
8: Check if "Are you sure you want to proceed...." message is displayed.

Expected result: "Are you sure you want to proceed...." message should not be display.

Actual result: "Are you sure you want to proceed...." message is displayed even when user have selected the music from "My Music" tab.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iVndiVkE5WDNIMUU

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.0.4-r2 (106)] on Google Pixel / 7.1.1.

**Comment by xiuie** [comment]
Works as designed. Music has to be selected on the tab they are on. This works like iOS
